# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.2
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XBiquadv2" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_BIQUADV2_BASEADDR" \
        "C_S_AXI_BIQUADV2_HIGHADDR"

    xdefine_config_file $drv_handle "xbiquadv2_g.c" "XBiquadv2" \
        "DEVICE_ID" \
        "C_S_AXI_BIQUADV2_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XBiquadv2" \
        "DEVICE_ID" \
        "C_S_AXI_BIQUADV2_BASEADDR" \
        "C_S_AXI_BIQUADV2_HIGHADDR"
}

