// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Biquadv2coeffs_HH_
#define _Biquadv2coeffs_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Biquadv2coeffs_coeffs_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_COEFFS_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_COEFFS_DATA_WIDTH = 32>
struct Biquadv2coeffs : public sc_module {
    // Port declarations 33
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<27> > out0b0_a0_V;
    sc_out< sc_logic > out0b0_a0_V_ap_vld;
    sc_out< sc_lv<27> > out0b1_a0_V;
    sc_out< sc_logic > out0b1_a0_V_ap_vld;
    sc_out< sc_lv<27> > out0b2_a0_V;
    sc_out< sc_logic > out0b2_a0_V_ap_vld;
    sc_out< sc_lv<27> > out0a1_a0_V;
    sc_out< sc_logic > out0a1_a0_V_ap_vld;
    sc_out< sc_lv<27> > out0a2_a0_V;
    sc_out< sc_logic > out0a2_a0_V_ap_vld;
    sc_in< sc_logic > s_axi_coeffs_AWVALID;
    sc_out< sc_logic > s_axi_coeffs_AWREADY;
    sc_in< sc_uint<C_S_AXI_COEFFS_ADDR_WIDTH> > s_axi_coeffs_AWADDR;
    sc_in< sc_logic > s_axi_coeffs_WVALID;
    sc_out< sc_logic > s_axi_coeffs_WREADY;
    sc_in< sc_uint<C_S_AXI_COEFFS_DATA_WIDTH> > s_axi_coeffs_WDATA;
    sc_in< sc_uint<C_S_AXI_COEFFS_DATA_WIDTH/8> > s_axi_coeffs_WSTRB;
    sc_in< sc_logic > s_axi_coeffs_ARVALID;
    sc_out< sc_logic > s_axi_coeffs_ARREADY;
    sc_in< sc_uint<C_S_AXI_COEFFS_ADDR_WIDTH> > s_axi_coeffs_ARADDR;
    sc_out< sc_logic > s_axi_coeffs_RVALID;
    sc_in< sc_logic > s_axi_coeffs_RREADY;
    sc_out< sc_uint<C_S_AXI_COEFFS_DATA_WIDTH> > s_axi_coeffs_RDATA;
    sc_out< sc_lv<2> > s_axi_coeffs_RRESP;
    sc_out< sc_logic > s_axi_coeffs_BVALID;
    sc_in< sc_logic > s_axi_coeffs_BREADY;
    sc_out< sc_lv<2> > s_axi_coeffs_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_signal< sc_logic > ap_var_for_const0;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    Biquadv2coeffs(sc_module_name name);
    SC_HAS_PROCESS(Biquadv2coeffs);

    ~Biquadv2coeffs();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Biquadv2coeffs_coeffs_s_axi<C_S_AXI_COEFFS_ADDR_WIDTH,C_S_AXI_COEFFS_DATA_WIDTH>* Biquadv2coeffs_coeffs_s_axi_U;
    sc_signal< sc_lv<27> > in0b0_a0_V;
    sc_signal< sc_lv<27> > in0b1_a0_V;
    sc_signal< sc_lv<27> > in0b2_a0_V;
    sc_signal< sc_lv<27> > in0a1_a0_V;
    sc_signal< sc_lv<27> > in0a2_a0_V;
    sc_signal< sc_logic > ap_rst_n_inv;
    static const sc_logic ap_const_logic_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_out0a1_a0_V();
    void thread_out0a1_a0_V_ap_vld();
    void thread_out0a2_a0_V();
    void thread_out0a2_a0_V_ap_vld();
    void thread_out0b0_a0_V();
    void thread_out0b0_a0_V_ap_vld();
    void thread_out0b1_a0_V();
    void thread_out0b1_a0_V_ap_vld();
    void thread_out0b2_a0_V();
    void thread_out0b2_a0_V_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
