# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.cache/wt [current_project]
set_property parent.project_path C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/family_support.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/common_types.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/pselect_f.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/address_decoder.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/slave_attachment.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/axi_lite_ipif.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/user_logic.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/iis_deser.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/iis_ser.vhd
  C:/Users/lions/Desktop/Github/ERTS-Assignments/a2/a2_ex6/lab4/ip_repo/zybo_audio_codec/zybo_audio_codec.srcs/sources_1/imports/i2s_audio/i2s_ctrl.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top i2s_ctrl -part xc7z010clg400-1


write_checkpoint -force -noxdef i2s_ctrl.dcp

catch { report_utilization -file i2s_ctrl_utilization_synth.rpt -pb i2s_ctrl_utilization_synth.pb }
