// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBIQUADV2END_H
#define XBIQUADV2END_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbiquadv2end_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Biquadv2_BaseAddress;
} XBiquadv2end_Config;
#endif

typedef struct {
    u32 Biquadv2_BaseAddress;
    u32 IsReady;
} XBiquadv2end;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBiquadv2end_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBiquadv2end_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBiquadv2end_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBiquadv2end_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBiquadv2end_Initialize(XBiquadv2end *InstancePtr, u16 DeviceId);
XBiquadv2end_Config* XBiquadv2end_LookupConfig(u16 DeviceId);
int XBiquadv2end_CfgInitialize(XBiquadv2end *InstancePtr, XBiquadv2end_Config *ConfigPtr);
#else
int XBiquadv2end_Initialize(XBiquadv2end *InstancePtr, const char* InstanceName);
int XBiquadv2end_Release(XBiquadv2end *InstancePtr);
#endif

void XBiquadv2end_Start(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_IsDone(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_IsIdle(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_IsReady(XBiquadv2end *InstancePtr);
void XBiquadv2end_EnableAutoRestart(XBiquadv2end *InstancePtr);
void XBiquadv2end_DisableAutoRestart(XBiquadv2end *InstancePtr);

void XBiquadv2end_Set_b0_a0_V(XBiquadv2end *InstancePtr, u32 Data);
u32 XBiquadv2end_Get_b0_a0_V(XBiquadv2end *InstancePtr);
void XBiquadv2end_Set_b1_a0_V(XBiquadv2end *InstancePtr, u32 Data);
u32 XBiquadv2end_Get_b1_a0_V(XBiquadv2end *InstancePtr);
void XBiquadv2end_Set_b2_a0_V(XBiquadv2end *InstancePtr, u32 Data);
u32 XBiquadv2end_Get_b2_a0_V(XBiquadv2end *InstancePtr);
void XBiquadv2end_Set_a1_a0_V(XBiquadv2end *InstancePtr, u32 Data);
u32 XBiquadv2end_Get_a1_a0_V(XBiquadv2end *InstancePtr);
void XBiquadv2end_Set_a2_a0_V(XBiquadv2end *InstancePtr, u32 Data);
u32 XBiquadv2end_Get_a2_a0_V(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_Get_outDataLeft_V(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_Get_outDataLeft_V_vld(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_Get_outDataRight_V(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_Get_outDataRight_V_vld(XBiquadv2end *InstancePtr);

void XBiquadv2end_InterruptGlobalEnable(XBiquadv2end *InstancePtr);
void XBiquadv2end_InterruptGlobalDisable(XBiquadv2end *InstancePtr);
void XBiquadv2end_InterruptEnable(XBiquadv2end *InstancePtr, u32 Mask);
void XBiquadv2end_InterruptDisable(XBiquadv2end *InstancePtr, u32 Mask);
void XBiquadv2end_InterruptClear(XBiquadv2end *InstancePtr, u32 Mask);
u32 XBiquadv2end_InterruptGetEnabled(XBiquadv2end *InstancePtr);
u32 XBiquadv2end_InterruptGetStatus(XBiquadv2end *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
