// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbiquadv2end.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBiquadv2end_CfgInitialize(XBiquadv2end *InstancePtr, XBiquadv2end_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Biquadv2_BaseAddress = ConfigPtr->Biquadv2_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBiquadv2end_Start(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL) & 0x80;
    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBiquadv2end_IsDone(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBiquadv2end_IsIdle(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBiquadv2end_IsReady(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBiquadv2end_EnableAutoRestart(XBiquadv2end *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL, 0x80);
}

void XBiquadv2end_DisableAutoRestart(XBiquadv2end *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_AP_CTRL, 0);
}

void XBiquadv2end_Set_b0_a0_V(XBiquadv2end *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_B0_A0_V_DATA, Data);
}

u32 XBiquadv2end_Get_b0_a0_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_B0_A0_V_DATA);
    return Data;
}

void XBiquadv2end_Set_b1_a0_V(XBiquadv2end *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_B1_A0_V_DATA, Data);
}

u32 XBiquadv2end_Get_b1_a0_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_B1_A0_V_DATA);
    return Data;
}

void XBiquadv2end_Set_b2_a0_V(XBiquadv2end *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_B2_A0_V_DATA, Data);
}

u32 XBiquadv2end_Get_b2_a0_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_B2_A0_V_DATA);
    return Data;
}

void XBiquadv2end_Set_a1_a0_V(XBiquadv2end *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_A1_A0_V_DATA, Data);
}

u32 XBiquadv2end_Get_a1_a0_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_A1_A0_V_DATA);
    return Data;
}

void XBiquadv2end_Set_a2_a0_V(XBiquadv2end *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_A2_A0_V_DATA, Data);
}

u32 XBiquadv2end_Get_a2_a0_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_A2_A0_V_DATA);
    return Data;
}

u32 XBiquadv2end_Get_outDataLeft_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_OUTDATALEFT_V_DATA);
    return Data;
}

u32 XBiquadv2end_Get_outDataLeft_V_vld(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_OUTDATALEFT_V_CTRL);
    return Data & 0x1;
}

u32 XBiquadv2end_Get_outDataRight_V(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_OUTDATARIGHT_V_DATA);
    return Data;
}

u32 XBiquadv2end_Get_outDataRight_V_vld(XBiquadv2end *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_OUTDATARIGHT_V_CTRL);
    return Data & 0x1;
}

void XBiquadv2end_InterruptGlobalEnable(XBiquadv2end *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_GIE, 1);
}

void XBiquadv2end_InterruptGlobalDisable(XBiquadv2end *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_GIE, 0);
}

void XBiquadv2end_InterruptEnable(XBiquadv2end *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_IER);
    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_IER, Register | Mask);
}

void XBiquadv2end_InterruptDisable(XBiquadv2end *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_IER);
    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_IER, Register & (~Mask));
}

void XBiquadv2end_InterruptClear(XBiquadv2end *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2end_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_ISR, Mask);
}

u32 XBiquadv2end_InterruptGetEnabled(XBiquadv2end *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_IER);
}

u32 XBiquadv2end_InterruptGetStatus(XBiquadv2end *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBiquadv2end_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2END_BIQUADV2_ADDR_ISR);
}

