// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbiquadv2between.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBiquadv2between_CfgInitialize(XBiquadv2between *InstancePtr, XBiquadv2between_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Biquadv2_BaseAddress = ConfigPtr->Biquadv2_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBiquadv2between_Set_b0_a0_V(XBiquadv2between *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2between_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_B0_A0_V_DATA, Data);
}

u32 XBiquadv2between_Get_b0_a0_V(XBiquadv2between *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2between_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_B0_A0_V_DATA);
    return Data;
}

void XBiquadv2between_Set_b1_a0_V(XBiquadv2between *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2between_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_B1_A0_V_DATA, Data);
}

u32 XBiquadv2between_Get_b1_a0_V(XBiquadv2between *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2between_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_B1_A0_V_DATA);
    return Data;
}

void XBiquadv2between_Set_b2_a0_V(XBiquadv2between *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2between_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_B2_A0_V_DATA, Data);
}

u32 XBiquadv2between_Get_b2_a0_V(XBiquadv2between *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2between_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_B2_A0_V_DATA);
    return Data;
}

void XBiquadv2between_Set_a1_a0_V(XBiquadv2between *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2between_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_A1_A0_V_DATA, Data);
}

u32 XBiquadv2between_Get_a1_a0_V(XBiquadv2between *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2between_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_A1_A0_V_DATA);
    return Data;
}

void XBiquadv2between_Set_a2_a0_V(XBiquadv2between *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2between_WriteReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_A2_A0_V_DATA, Data);
}

u32 XBiquadv2between_Get_a2_a0_V(XBiquadv2between *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2between_ReadReg(InstancePtr->Biquadv2_BaseAddress, XBIQUADV2BETWEEN_BIQUADV2_ADDR_A2_A0_V_DATA);
    return Data;
}

