// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// biquadv2
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of b0_a0_V
//        bit 26~0 - b0_a0_V[26:0] (Read/Write)
//        others   - reserved
// 0x14 : reserved
// 0x18 : Data signal of b1_a0_V
//        bit 26~0 - b1_a0_V[26:0] (Read/Write)
//        others   - reserved
// 0x1c : reserved
// 0x20 : Data signal of b2_a0_V
//        bit 26~0 - b2_a0_V[26:0] (Read/Write)
//        others   - reserved
// 0x24 : reserved
// 0x28 : Data signal of a1_a0_V
//        bit 26~0 - a1_a0_V[26:0] (Read/Write)
//        others   - reserved
// 0x2c : reserved
// 0x30 : Data signal of a2_a0_V
//        bit 26~0 - a2_a0_V[26:0] (Read/Write)
//        others   - reserved
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBIQUADV2BETWEEN_BIQUADV2_ADDR_B0_A0_V_DATA 0x10
#define XBIQUADV2BETWEEN_BIQUADV2_BITS_B0_A0_V_DATA 27
#define XBIQUADV2BETWEEN_BIQUADV2_ADDR_B1_A0_V_DATA 0x18
#define XBIQUADV2BETWEEN_BIQUADV2_BITS_B1_A0_V_DATA 27
#define XBIQUADV2BETWEEN_BIQUADV2_ADDR_B2_A0_V_DATA 0x20
#define XBIQUADV2BETWEEN_BIQUADV2_BITS_B2_A0_V_DATA 27
#define XBIQUADV2BETWEEN_BIQUADV2_ADDR_A1_A0_V_DATA 0x28
#define XBIQUADV2BETWEEN_BIQUADV2_BITS_A1_A0_V_DATA 27
#define XBIQUADV2BETWEEN_BIQUADV2_ADDR_A2_A0_V_DATA 0x30
#define XBIQUADV2BETWEEN_BIQUADV2_BITS_A2_A0_V_DATA 27

