// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBIQUADV2_H
#define XBIQUADV2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbiquadv2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Biquadv2_BaseAddress;
} XBiquadv2_Config;
#endif

typedef struct {
    u32 Biquadv2_BaseAddress;
    u32 IsReady;
} XBiquadv2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBiquadv2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBiquadv2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBiquadv2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBiquadv2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBiquadv2_Initialize(XBiquadv2 *InstancePtr, u16 DeviceId);
XBiquadv2_Config* XBiquadv2_LookupConfig(u16 DeviceId);
int XBiquadv2_CfgInitialize(XBiquadv2 *InstancePtr, XBiquadv2_Config *ConfigPtr);
#else
int XBiquadv2_Initialize(XBiquadv2 *InstancePtr, const char* InstanceName);
int XBiquadv2_Release(XBiquadv2 *InstancePtr);
#endif

void XBiquadv2_Start(XBiquadv2 *InstancePtr);
u32 XBiquadv2_IsDone(XBiquadv2 *InstancePtr);
u32 XBiquadv2_IsIdle(XBiquadv2 *InstancePtr);
u32 XBiquadv2_IsReady(XBiquadv2 *InstancePtr);
void XBiquadv2_EnableAutoRestart(XBiquadv2 *InstancePtr);
void XBiquadv2_DisableAutoRestart(XBiquadv2 *InstancePtr);

void XBiquadv2_Set_inData_V(XBiquadv2 *InstancePtr, u32 Data);
u32 XBiquadv2_Get_inData_V(XBiquadv2 *InstancePtr);
u32 XBiquadv2_Get_outData_V(XBiquadv2 *InstancePtr);
u32 XBiquadv2_Get_outData_V_vld(XBiquadv2 *InstancePtr);

void XBiquadv2_InterruptGlobalEnable(XBiquadv2 *InstancePtr);
void XBiquadv2_InterruptGlobalDisable(XBiquadv2 *InstancePtr);
void XBiquadv2_InterruptEnable(XBiquadv2 *InstancePtr, u32 Mask);
void XBiquadv2_InterruptDisable(XBiquadv2 *InstancePtr, u32 Mask);
void XBiquadv2_InterruptClear(XBiquadv2 *InstancePtr, u32 Mask);
u32 XBiquadv2_InterruptGetEnabled(XBiquadv2 *InstancePtr);
u32 XBiquadv2_InterruptGetStatus(XBiquadv2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
