// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBIQUADV2START_H
#define XBIQUADV2START_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbiquadv2start_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Biquadv2_BaseAddress;
} XBiquadv2start_Config;
#endif

typedef struct {
    u32 Biquadv2_BaseAddress;
    u32 IsReady;
} XBiquadv2start;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBiquadv2start_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBiquadv2start_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBiquadv2start_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBiquadv2start_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBiquadv2start_Initialize(XBiquadv2start *InstancePtr, u16 DeviceId);
XBiquadv2start_Config* XBiquadv2start_LookupConfig(u16 DeviceId);
int XBiquadv2start_CfgInitialize(XBiquadv2start *InstancePtr, XBiquadv2start_Config *ConfigPtr);
#else
int XBiquadv2start_Initialize(XBiquadv2start *InstancePtr, const char* InstanceName);
int XBiquadv2start_Release(XBiquadv2start *InstancePtr);
#endif


void XBiquadv2start_Set_b0_a0_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_b0_a0_V(XBiquadv2start *InstancePtr);
void XBiquadv2start_Set_b1_a0_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_b1_a0_V(XBiquadv2start *InstancePtr);
void XBiquadv2start_Set_b2_a0_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_b2_a0_V(XBiquadv2start *InstancePtr);
void XBiquadv2start_Set_a1_a0_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_a1_a0_V(XBiquadv2start *InstancePtr);
void XBiquadv2start_Set_a2_a0_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_a2_a0_V(XBiquadv2start *InstancePtr);
void XBiquadv2start_Set_inDataLeft_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_inDataLeft_V(XBiquadv2start *InstancePtr);
void XBiquadv2start_Set_inDataRight_V(XBiquadv2start *InstancePtr, u32 Data);
u32 XBiquadv2start_Get_inDataRight_V(XBiquadv2start *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
