// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_biquadv2start (
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b0_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b1_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b2_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> a1_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> a2_a0,
ap_fixed<24, 1, (ap_q_mode) 0, (ap_o_mode)0, 0> inDataLeft,
ap_fixed<24, 1, (ap_q_mode) 0, (ap_o_mode)0, 0>* outDataLeft);
