// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#define AP_INT_MAX_W 32678

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "b0_a0_V"
#define AUTOTB_TVIN_b0_a0_V  "../tv/cdatafile/c.biquadv2start.autotvin_b0_a0_V.dat"
// wrapc file define: "b1_a0_V"
#define AUTOTB_TVIN_b1_a0_V  "../tv/cdatafile/c.biquadv2start.autotvin_b1_a0_V.dat"
// wrapc file define: "b2_a0_V"
#define AUTOTB_TVIN_b2_a0_V  "../tv/cdatafile/c.biquadv2start.autotvin_b2_a0_V.dat"
// wrapc file define: "a1_a0_V"
#define AUTOTB_TVIN_a1_a0_V  "../tv/cdatafile/c.biquadv2start.autotvin_a1_a0_V.dat"
// wrapc file define: "a2_a0_V"
#define AUTOTB_TVIN_a2_a0_V  "../tv/cdatafile/c.biquadv2start.autotvin_a2_a0_V.dat"
// wrapc file define: "inDataLeft_V"
#define AUTOTB_TVIN_inDataLeft_V  "../tv/cdatafile/c.biquadv2start.autotvin_inDataLeft_V.dat"
// wrapc file define: "outDataLeft_V"
#define AUTOTB_TVOUT_outDataLeft_V  "../tv/cdatafile/c.biquadv2start.autotvout_outDataLeft_V.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "outDataLeft_V"
#define AUTOTB_TVOUT_PC_outDataLeft_V  "../tv/rtldatafile/rtl.biquadv2start.autotvout_outDataLeft_V.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			b0_a0_V_depth = 0;
			b1_a0_V_depth = 0;
			b2_a0_V_depth = 0;
			a1_a0_V_depth = 0;
			a2_a0_V_depth = 0;
			inDataLeft_V_depth = 0;
			outDataLeft_V_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{b0_a0_V " << b0_a0_V_depth << "}\n";
			total_list << "{b1_a0_V " << b1_a0_V_depth << "}\n";
			total_list << "{b2_a0_V " << b2_a0_V_depth << "}\n";
			total_list << "{a1_a0_V " << a1_a0_V_depth << "}\n";
			total_list << "{a2_a0_V " << a2_a0_V_depth << "}\n";
			total_list << "{inDataLeft_V " << inDataLeft_V_depth << "}\n";
			total_list << "{outDataLeft_V " << outDataLeft_V_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int b0_a0_V_depth;
		int b1_a0_V_depth;
		int b2_a0_V_depth;
		int a1_a0_V_depth;
		int a2_a0_V_depth;
		int inDataLeft_V_depth;
		int outDataLeft_V_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern void biquadv2start (
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b0_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b1_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b2_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> a1_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> a2_a0,
ap_fixed<24, 1, (ap_q_mode) 0, (ap_o_mode)0, 0> inDataLeft,
ap_fixed<24, 1, (ap_q_mode) 0, (ap_o_mode)0, 0>* outDataLeft);

void AESL_WRAP_biquadv2start (
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b0_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b1_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> b2_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> a1_a0,
ap_fixed<27, 3, (ap_q_mode) 0, (ap_o_mode)0, 0> a2_a0,
ap_fixed<24, 1, (ap_q_mode) 0, (ap_o_mode)0, 0> inDataLeft,
ap_fixed<24, 1, (ap_q_mode) 0, (ap_o_mode)0, 0>* outDataLeft)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "outDataLeft_V"
		aesl_fh.read(AUTOTB_TVOUT_PC_outDataLeft_V, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_outDataLeft_V, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_outDataLeft_V, AESL_token); // data

			sc_bv<24> *outDataLeft_V_pc_buffer = new sc_bv<24>[1];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'outDataLeft_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'outDataLeft_V', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					outDataLeft_V_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_outDataLeft_V, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_outDataLeft_V))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: outDataLeft_V
				{
					// bitslice(23, 0)
					// {
						// celement: outDataLeft.V(23, 0)
						// {
							sc_lv<24>* outDataLeft_V_lv0_0_0_1 = new sc_lv<24>[1];
						// }
					// }

					// bitslice(23, 0)
					{
						int hls_map_index = 0;
						// celement: outDataLeft.V(23, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								if (&(outDataLeft[0]) != NULL) // check the null address if the c port is array or others
								{
									outDataLeft_V_lv0_0_0_1[hls_map_index].range(23, 0) = sc_bv<24>(outDataLeft_V_pc_buffer[hls_map_index].range(23, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(23, 0)
					{
						int hls_map_index = 0;
						// celement: outDataLeft.V(23, 0)
						{
							// carray: (0) => (0) @ (1)
							for (int i_0 = 0; i_0 <= 0; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : outDataLeft[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : outDataLeft[0]
								// output_left_conversion : (outDataLeft[i_0]).range()
								// output_type_conversion : (outDataLeft_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str()
								if (&(outDataLeft[0]) != NULL) // check the null address if the c port is array or others
								{
									(outDataLeft[i_0]).range() = (outDataLeft_V_lv0_0_0_1[hls_map_index]).to_string(SC_BIN).c_str();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] outDataLeft_V_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "b0_a0_V"
		char* tvin_b0_a0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_b0_a0_V);

		// "b1_a0_V"
		char* tvin_b1_a0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_b1_a0_V);

		// "b2_a0_V"
		char* tvin_b2_a0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_b2_a0_V);

		// "a1_a0_V"
		char* tvin_a1_a0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_a1_a0_V);

		// "a2_a0_V"
		char* tvin_a2_a0_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_a2_a0_V);

		// "inDataLeft_V"
		char* tvin_inDataLeft_V = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_inDataLeft_V);

		// "outDataLeft_V"
		char* tvout_outDataLeft_V = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_outDataLeft_V);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_b0_a0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_b0_a0_V, tvin_b0_a0_V);

		sc_bv<27> b0_a0_V_tvin_wrapc_buffer;

		// RTL Name: b0_a0_V
		{
			// bitslice(26, 0)
			{
				// celement: b0_a0.V(26, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : b0_a0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : b0_a0
						// regulate_c_name       : b0_a0_V
						// input_type_conversion : (b0_a0).range().to_string(SC_BIN).c_str()
						if (&(b0_a0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<27> b0_a0_V_tmp_mem;
							b0_a0_V_tmp_mem = (b0_a0).range().to_string(SC_BIN).c_str();
							b0_a0_V_tvin_wrapc_buffer.range(26, 0) = b0_a0_V_tmp_mem.range(26, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_b0_a0_V, "%s\n", (b0_a0_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_b0_a0_V, tvin_b0_a0_V);
		}

		tcl_file.set_num(1, &tcl_file.b0_a0_V_depth);
		sprintf(tvin_b0_a0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_b0_a0_V, tvin_b0_a0_V);

		// [[transaction]]
		sprintf(tvin_b1_a0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_b1_a0_V, tvin_b1_a0_V);

		sc_bv<27> b1_a0_V_tvin_wrapc_buffer;

		// RTL Name: b1_a0_V
		{
			// bitslice(26, 0)
			{
				// celement: b1_a0.V(26, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : b1_a0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : b1_a0
						// regulate_c_name       : b1_a0_V
						// input_type_conversion : (b1_a0).range().to_string(SC_BIN).c_str()
						if (&(b1_a0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<27> b1_a0_V_tmp_mem;
							b1_a0_V_tmp_mem = (b1_a0).range().to_string(SC_BIN).c_str();
							b1_a0_V_tvin_wrapc_buffer.range(26, 0) = b1_a0_V_tmp_mem.range(26, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_b1_a0_V, "%s\n", (b1_a0_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_b1_a0_V, tvin_b1_a0_V);
		}

		tcl_file.set_num(1, &tcl_file.b1_a0_V_depth);
		sprintf(tvin_b1_a0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_b1_a0_V, tvin_b1_a0_V);

		// [[transaction]]
		sprintf(tvin_b2_a0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_b2_a0_V, tvin_b2_a0_V);

		sc_bv<27> b2_a0_V_tvin_wrapc_buffer;

		// RTL Name: b2_a0_V
		{
			// bitslice(26, 0)
			{
				// celement: b2_a0.V(26, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : b2_a0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : b2_a0
						// regulate_c_name       : b2_a0_V
						// input_type_conversion : (b2_a0).range().to_string(SC_BIN).c_str()
						if (&(b2_a0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<27> b2_a0_V_tmp_mem;
							b2_a0_V_tmp_mem = (b2_a0).range().to_string(SC_BIN).c_str();
							b2_a0_V_tvin_wrapc_buffer.range(26, 0) = b2_a0_V_tmp_mem.range(26, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_b2_a0_V, "%s\n", (b2_a0_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_b2_a0_V, tvin_b2_a0_V);
		}

		tcl_file.set_num(1, &tcl_file.b2_a0_V_depth);
		sprintf(tvin_b2_a0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_b2_a0_V, tvin_b2_a0_V);

		// [[transaction]]
		sprintf(tvin_a1_a0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_a1_a0_V, tvin_a1_a0_V);

		sc_bv<27> a1_a0_V_tvin_wrapc_buffer;

		// RTL Name: a1_a0_V
		{
			// bitslice(26, 0)
			{
				// celement: a1_a0.V(26, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : a1_a0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : a1_a0
						// regulate_c_name       : a1_a0_V
						// input_type_conversion : (a1_a0).range().to_string(SC_BIN).c_str()
						if (&(a1_a0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<27> a1_a0_V_tmp_mem;
							a1_a0_V_tmp_mem = (a1_a0).range().to_string(SC_BIN).c_str();
							a1_a0_V_tvin_wrapc_buffer.range(26, 0) = a1_a0_V_tmp_mem.range(26, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_a1_a0_V, "%s\n", (a1_a0_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_a1_a0_V, tvin_a1_a0_V);
		}

		tcl_file.set_num(1, &tcl_file.a1_a0_V_depth);
		sprintf(tvin_a1_a0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_a1_a0_V, tvin_a1_a0_V);

		// [[transaction]]
		sprintf(tvin_a2_a0_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_a2_a0_V, tvin_a2_a0_V);

		sc_bv<27> a2_a0_V_tvin_wrapc_buffer;

		// RTL Name: a2_a0_V
		{
			// bitslice(26, 0)
			{
				// celement: a2_a0.V(26, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : a2_a0
						// sub_1st_elem          : 
						// ori_name_1st_elem     : a2_a0
						// regulate_c_name       : a2_a0_V
						// input_type_conversion : (a2_a0).range().to_string(SC_BIN).c_str()
						if (&(a2_a0) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<27> a2_a0_V_tmp_mem;
							a2_a0_V_tmp_mem = (a2_a0).range().to_string(SC_BIN).c_str();
							a2_a0_V_tvin_wrapc_buffer.range(26, 0) = a2_a0_V_tmp_mem.range(26, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_a2_a0_V, "%s\n", (a2_a0_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_a2_a0_V, tvin_a2_a0_V);
		}

		tcl_file.set_num(1, &tcl_file.a2_a0_V_depth);
		sprintf(tvin_a2_a0_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_a2_a0_V, tvin_a2_a0_V);

		// [[transaction]]
		sprintf(tvin_inDataLeft_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_inDataLeft_V, tvin_inDataLeft_V);

		sc_bv<24> inDataLeft_V_tvin_wrapc_buffer;

		// RTL Name: inDataLeft_V
		{
			// bitslice(23, 0)
			{
				// celement: inDataLeft.V(23, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : inDataLeft
						// sub_1st_elem          : 
						// ori_name_1st_elem     : inDataLeft
						// regulate_c_name       : inDataLeft_V
						// input_type_conversion : (inDataLeft).range().to_string(SC_BIN).c_str()
						if (&(inDataLeft) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<24> inDataLeft_V_tmp_mem;
							inDataLeft_V_tmp_mem = (inDataLeft).range().to_string(SC_BIN).c_str();
							inDataLeft_V_tvin_wrapc_buffer.range(23, 0) = inDataLeft_V_tmp_mem.range(23, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_inDataLeft_V, "%s\n", (inDataLeft_V_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_inDataLeft_V, tvin_inDataLeft_V);
		}

		tcl_file.set_num(1, &tcl_file.inDataLeft_V_depth);
		sprintf(tvin_inDataLeft_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_inDataLeft_V, tvin_inDataLeft_V);

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		biquadv2start(b0_a0, b1_a0, b2_a0, a1_a0, a2_a0, inDataLeft, outDataLeft);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_outDataLeft_V, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_outDataLeft_V, tvout_outDataLeft_V);

		sc_bv<24>* outDataLeft_V_tvout_wrapc_buffer = new sc_bv<24>[1];

		// RTL Name: outDataLeft_V
		{
			// bitslice(23, 0)
			{
				int hls_map_index = 0;
				// celement: outDataLeft.V(23, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : outDataLeft[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : outDataLeft[0]
						// regulate_c_name       : outDataLeft_V
						// input_type_conversion : (outDataLeft[i_0]).range().to_string(SC_BIN).c_str()
						if (&(outDataLeft[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<24> outDataLeft_V_tmp_mem;
							outDataLeft_V_tmp_mem = (outDataLeft[i_0]).range().to_string(SC_BIN).c_str();
							outDataLeft_V_tvout_wrapc_buffer[hls_map_index].range(23, 0) = outDataLeft_V_tmp_mem.range(23, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_outDataLeft_V, "%s\n", (outDataLeft_V_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_outDataLeft_V, tvout_outDataLeft_V);
		}

		tcl_file.set_num(1, &tcl_file.outDataLeft_V_depth);
		sprintf(tvout_outDataLeft_V, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_outDataLeft_V, tvout_outDataLeft_V);

		// release memory allocation
		delete [] outDataLeft_V_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "b0_a0_V"
		delete [] tvin_b0_a0_V;
		// release memory allocation: "b1_a0_V"
		delete [] tvin_b1_a0_V;
		// release memory allocation: "b2_a0_V"
		delete [] tvin_b2_a0_V;
		// release memory allocation: "a1_a0_V"
		delete [] tvin_a1_a0_V;
		// release memory allocation: "a2_a0_V"
		delete [] tvin_a2_a0_V;
		// release memory allocation: "inDataLeft_V"
		delete [] tvin_inDataLeft_V;
		// release memory allocation: "outDataLeft_V"
		delete [] tvout_outDataLeft_V;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

