// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbiquad.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBiquad_CfgInitialize(XBiquad *InstancePtr, XBiquad_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Biquad_io_BaseAddress = ConfigPtr->Biquad_io_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBiquad_SetIndata(XBiquad *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquad_WriteReg(InstancePtr->Biquad_io_BaseAddress, XBIQUAD_BIQUAD_IO_ADDR_INDATA_DATA, Data);
}

u32 XBiquad_GetIndata(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Biquad_io_BaseAddress, XBIQUAD_BIQUAD_IO_ADDR_INDATA_DATA);
    return Data;
}

u32 XBiquad_GetOutdata(XBiquad *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquad_ReadReg(InstancePtr->Biquad_io_BaseAddress, XBIQUAD_BIQUAD_IO_ADDR_OUTDATA_DATA);
    return Data;
}

