// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbiquadv2coeffs.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBiquadv2coeffs_CfgInitialize(XBiquadv2coeffs *InstancePtr, XBiquadv2coeffs_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Coeffs_BaseAddress = ConfigPtr->Coeffs_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBiquadv2coeffs_Set_in0b0_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2coeffs_WriteReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0B0_A0_V_DATA, Data);
}

u32 XBiquadv2coeffs_Get_in0b0_a0_V(XBiquadv2coeffs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2coeffs_ReadReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0B0_A0_V_DATA);
    return Data;
}

void XBiquadv2coeffs_Set_in0b1_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2coeffs_WriteReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0B1_A0_V_DATA, Data);
}

u32 XBiquadv2coeffs_Get_in0b1_a0_V(XBiquadv2coeffs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2coeffs_ReadReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0B1_A0_V_DATA);
    return Data;
}

void XBiquadv2coeffs_Set_in0b2_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2coeffs_WriteReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0B2_A0_V_DATA, Data);
}

u32 XBiquadv2coeffs_Get_in0b2_a0_V(XBiquadv2coeffs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2coeffs_ReadReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0B2_A0_V_DATA);
    return Data;
}

void XBiquadv2coeffs_Set_in0a1_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2coeffs_WriteReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0A1_A0_V_DATA, Data);
}

u32 XBiquadv2coeffs_Get_in0a1_a0_V(XBiquadv2coeffs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2coeffs_ReadReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0A1_A0_V_DATA);
    return Data;
}

void XBiquadv2coeffs_Set_in0a2_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBiquadv2coeffs_WriteReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0A2_A0_V_DATA, Data);
}

u32 XBiquadv2coeffs_Get_in0a2_a0_V(XBiquadv2coeffs *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBiquadv2coeffs_ReadReg(InstancePtr->Coeffs_BaseAddress, XBIQUADV2COEFFS_COEFFS_ADDR_IN0A2_A0_V_DATA);
    return Data;
}

