// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbiquadv2.h"

extern XBiquadv2_Config XBiquadv2_ConfigTable[];

XBiquadv2_Config *XBiquadv2_LookupConfig(u16 DeviceId) {
	XBiquadv2_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBIQUADV2_NUM_INSTANCES; Index++) {
		if (XBiquadv2_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBiquadv2_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBiquadv2_Initialize(XBiquadv2 *InstancePtr, u16 DeviceId) {
	XBiquadv2_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBiquadv2_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBiquadv2_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

