#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("out0b0_a0_V", 27, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("out0b0_a0_V_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("out0b1_a0_V", 27, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("out0b1_a0_V_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("out0b2_a0_V", 27, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("out0b2_a0_V_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("out0a1_a0_V", 27, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("out0a1_a0_V_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("out0a2_a0_V", 27, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("out0a2_a0_V_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("s_axi_coeffs_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_AWADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_ARADDR", 6, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_coeffs_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_coeffs_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "Biquadv2coeffs";
