// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="biquadv2start,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.416000,HLS_SYN_LAT=49,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=3,HLS_SYN_FF=1662,HLS_SYN_LUT=1407}" *)

module biquadv2start (
        ap_clk,
        ap_rst_n,
        outDataLeft_V,
        outDataLeft_V_ap_vld,
        outDataLeft_V_ap_ack,
        outDataRight_V,
        outDataRight_V_ap_vld,
        outDataRight_V_ap_ack,
        s_axi_biquadv2_AWVALID,
        s_axi_biquadv2_AWREADY,
        s_axi_biquadv2_AWADDR,
        s_axi_biquadv2_WVALID,
        s_axi_biquadv2_WREADY,
        s_axi_biquadv2_WDATA,
        s_axi_biquadv2_WSTRB,
        s_axi_biquadv2_ARVALID,
        s_axi_biquadv2_ARREADY,
        s_axi_biquadv2_ARADDR,
        s_axi_biquadv2_RVALID,
        s_axi_biquadv2_RREADY,
        s_axi_biquadv2_RDATA,
        s_axi_biquadv2_RRESP,
        s_axi_biquadv2_BVALID,
        s_axi_biquadv2_BREADY,
        s_axi_biquadv2_BRESP
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;
parameter    C_S_AXI_BIQUADV2_DATA_WIDTH = 32;
parameter    C_S_AXI_BIQUADV2_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_BIQUADV2_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [23:0] outDataLeft_V;
output   outDataLeft_V_ap_vld;
input   outDataLeft_V_ap_ack;
output  [23:0] outDataRight_V;
output   outDataRight_V_ap_vld;
input   outDataRight_V_ap_ack;
input   s_axi_biquadv2_AWVALID;
output   s_axi_biquadv2_AWREADY;
input  [C_S_AXI_BIQUADV2_ADDR_WIDTH - 1:0] s_axi_biquadv2_AWADDR;
input   s_axi_biquadv2_WVALID;
output   s_axi_biquadv2_WREADY;
input  [C_S_AXI_BIQUADV2_DATA_WIDTH - 1:0] s_axi_biquadv2_WDATA;
input  [C_S_AXI_BIQUADV2_WSTRB_WIDTH - 1:0] s_axi_biquadv2_WSTRB;
input   s_axi_biquadv2_ARVALID;
output   s_axi_biquadv2_ARREADY;
input  [C_S_AXI_BIQUADV2_ADDR_WIDTH - 1:0] s_axi_biquadv2_ARADDR;
output   s_axi_biquadv2_RVALID;
input   s_axi_biquadv2_RREADY;
output  [C_S_AXI_BIQUADV2_DATA_WIDTH - 1:0] s_axi_biquadv2_RDATA;
output  [1:0] s_axi_biquadv2_RRESP;
output   s_axi_biquadv2_BVALID;
input   s_axi_biquadv2_BREADY;
output  [1:0] s_axi_biquadv2_BRESP;

reg outDataLeft_V_ap_vld;
reg outDataRight_V_ap_vld;

reg    ap_rst_n_inv;
wire   [26:0] b0_a0_V;
wire   [26:0] b1_a0_V;
wire   [26:0] b2_a0_V;
wire   [26:0] a1_a0_V;
wire   [26:0] a2_a0_V;
wire   [23:0] inDataLeft_V;
wire   [23:0] inDataRight_V;
reg   [3:0] array_r_address0;
reg    array_r_ce0;
reg    array_r_we0;
reg   [26:0] array_r_d0;
wire   [26:0] array_r_q0;
reg   [3:0] array_r_address1;
reg    array_r_ce1;
reg    array_r_we1;
reg   [26:0] array_r_d1;
wire   [26:0] array_r_q1;
reg    outDataLeft_V_blk_n;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state16;
reg    outDataRight_V_blk_n;
wire   [50:0] grp_fu_279_p2;
reg   [50:0] reg_301;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [23:0] inDataRight_V_read_reg_863;
wire    ap_CS_fsm_state1;
reg   [23:0] inDataLeft_V_read_reg_868;
reg   [26:0] a2_a0_V_read_reg_873;
reg   [26:0] a1_a0_V_read_reg_878;
reg   [26:0] b2_a0_V_read_reg_883;
wire   [26:0] inDataLeft_V_trunc_fu_305_p1;
reg   [26:0] inDataLeft_V_trunc_reg_888;
wire    ap_CS_fsm_state4;
wire   [26:0] inDataRight_V_trunc_fu_309_p1;
reg   [26:0] inDataRight_V_trunc_reg_893;
wire   [2:0] i_V_fu_319_p2;
reg   [2:0] i_V_reg_901;
wire    ap_CS_fsm_state5;
wire   [3:0] tmp_3_cast_fu_330_p1;
reg   [3:0] tmp_3_cast_reg_906;
wire   [0:0] tmp_2_fu_313_p2;
reg   [26:0] array_load_4_reg_921;
wire    ap_CS_fsm_state6;
wire   [23:0] tmp_20_fu_345_p1;
reg   [23:0] tmp_20_reg_926;
wire  signed [50:0] OP1_V_fu_359_p1;
reg  signed [50:0] OP1_V_reg_936;
wire    ap_CS_fsm_state7;
wire  signed [50:0] OP2_V_fu_363_p1;
wire   [23:0] tmp_26_fu_367_p1;
reg   [23:0] tmp_26_reg_946;
reg   [0:0] tmp_22_reg_951;
wire  signed [50:0] OP2_V_1_fu_371_p1;
wire   [50:0] p_Val2_2_fu_387_p2;
reg   [50:0] p_Val2_2_reg_961;
reg   [0:0] signbit_reg_966;
wire   [23:0] p_Val2_4_fu_422_p2;
reg   [23:0] p_Val2_4_reg_972;
wire   [0:0] newsignbit_fu_428_p3;
reg   [0:0] newsignbit_reg_978;
wire   [0:0] carry_fu_442_p2;
reg   [0:0] carry_reg_984;
wire   [0:0] Range2_all_ones_fu_458_p2;
reg   [0:0] Range2_all_ones_reg_991;
wire   [0:0] Range1_all_ones_fu_474_p2;
reg   [0:0] Range1_all_ones_reg_996;
wire   [0:0] Range1_all_zeros_fu_480_p2;
reg   [0:0] Range1_all_zeros_reg_1003;
reg   [0:0] tmp_28_reg_1008;
wire   [0:0] p_38_i_i_fu_515_p2;
reg   [0:0] p_38_i_i_reg_1013;
wire    ap_CS_fsm_state10;
wire   [0:0] tmp_9_fu_530_p2;
reg   [0:0] tmp_9_reg_1018;
wire   [0:0] brmerge40_demorgan_i_fu_541_p2;
reg   [0:0] brmerge40_demorgan_i_reg_1023;
wire   [0:0] underflow_fu_558_p2;
reg   [0:0] underflow_reg_1028;
wire   [0:0] brmerge_i_i_i_fu_563_p2;
reg   [0:0] brmerge_i_i_i_reg_1033;
wire   [50:0] p_Val2_7_fu_581_p2;
reg   [50:0] p_Val2_7_reg_1038;
reg   [0:0] signbit_1_reg_1043;
wire   [23:0] p_Val2_9_fu_616_p2;
reg   [23:0] p_Val2_9_reg_1049;
wire   [0:0] newsignbit_1_fu_622_p3;
reg   [0:0] newsignbit_1_reg_1055;
wire   [0:0] carry_1_fu_636_p2;
reg   [0:0] carry_1_reg_1061;
wire   [0:0] Range2_all_ones_1_fu_652_p2;
reg   [0:0] Range2_all_ones_1_reg_1068;
wire   [0:0] Range1_all_ones_1_fu_668_p2;
reg   [0:0] Range1_all_ones_1_reg_1073;
wire   [0:0] Range1_all_zeros_1_fu_674_p2;
reg   [0:0] Range1_all_zeros_1_reg_1080;
wire   [23:0] resultLeft_V_fu_701_p3;
reg   [23:0] resultLeft_V_reg_1085;
wire    ap_CS_fsm_state11;
wire   [0:0] p_38_i_i1_fu_738_p2;
reg   [0:0] p_38_i_i1_reg_1090;
wire   [0:0] tmp_16_fu_753_p2;
reg   [0:0] tmp_16_reg_1095;
wire   [0:0] brmerge40_demorgan_i_1_fu_764_p2;
reg   [0:0] brmerge40_demorgan_i_1_reg_1100;
wire   [0:0] underflow_1_fu_781_p2;
reg   [0:0] underflow_1_reg_1105;
wire   [0:0] brmerge_i_i_i1_fu_786_p2;
reg   [0:0] brmerge_i_i_i1_reg_1110;
wire   [23:0] resultRight_V_fu_813_p3;
wire    ap_CS_fsm_state12;
wire   [23:0] tmp_4_fu_821_p1;
reg   [23:0] tmp_4_reg_1120;
wire    ap_CS_fsm_state13;
wire   [23:0] tmp_17_fu_825_p1;
reg   [23:0] tmp_17_reg_1125;
wire   [23:0] tmp_18_fu_838_p1;
reg   [23:0] tmp_18_reg_1130;
wire    ap_CS_fsm_state14;
wire   [23:0] tmp_19_fu_842_p1;
reg   [23:0] tmp_19_reg_1135;
reg   [23:0] p_Val2_5_reg_242;
reg   [23:0] p_Val2_s_reg_255;
reg   [2:0] p_s_reg_268;
wire   [31:0] tmp_3_fu_325_p1;
wire   [31:0] addr5_cast_fu_340_p1;
wire   [31:0] addr1_cast_fu_354_p1;
reg    ap_reg_ioackin_outDataLeft_V_ap_ack;
reg    ap_sig_ioackin_outDataLeft_V_ap_ack;
reg    ap_sig_ioackin_outDataRight_V_ap_ack;
reg    ap_block_state16_io;
reg    ap_reg_ioackin_outDataRight_V_ap_ack;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [26:0] samples_V_load11_tru_fu_829_p1;
wire   [26:0] p_Val2_trunc_fu_833_p1;
wire    ap_CS_fsm_state15;
wire   [26:0] samples_V_load_114_t_fu_846_p1;
wire   [26:0] samples_V_load_217_t_fu_850_p1;
wire   [26:0] p_Val2_5_trunc_fu_854_p1;
wire    ap_CS_fsm_state17;
wire   [26:0] samples_V_load_320_t_fu_859_p1;
reg  signed [26:0] grp_fu_279_p0;
reg  signed [23:0] grp_fu_279_p1;
wire   [3:0] addr5_fu_334_p2;
wire   [3:0] addr1_fu_349_p2;
wire   [47:0] tmp_8_fu_375_p3;
wire  signed [50:0] tmp_8_cast_fu_383_p1;
wire   [23:0] p_Val2_3_fu_401_p4;
wire   [23:0] tmp_5_fu_411_p1;
wire   [0:0] tmp_23_fu_414_p3;
wire   [0:0] tmp_s_fu_436_p2;
wire   [1:0] tmp_6_fu_448_p4;
wire   [2:0] tmp_7_fu_464_p4;
wire   [0:0] tmp_25_fu_486_p3;
wire   [0:0] tmp_1_fu_498_p2;
wire   [0:0] p_41_i_i_fu_504_p2;
wire   [0:0] deleted_zeros_fu_493_p3;
wire   [0:0] p_not_i_i_fu_519_p2;
wire   [0:0] brmerge_i_i_fu_525_p2;
wire   [0:0] deleted_ones_fu_509_p3;
wire   [0:0] tmp_demorgan_fu_546_p2;
wire   [0:0] tmp_fu_552_p2;
wire   [0:0] overflow_fu_535_p2;
wire   [47:0] tmp_10_fu_569_p3;
wire  signed [50:0] tmp_13_cast_fu_577_p1;
wire   [23:0] p_Val2_8_fu_595_p4;
wire   [23:0] tmp_11_fu_605_p1;
wire   [0:0] tmp_29_fu_608_p3;
wire   [0:0] tmp_12_fu_630_p2;
wire   [1:0] tmp_13_fu_642_p4;
wire   [2:0] tmp_14_fu_658_p4;
wire   [0:0] tmp1_fu_680_p2;
wire   [0:0] underflow_not_fu_684_p2;
wire   [23:0] p_Val2_4_mux_fu_689_p3;
wire   [23:0] p_Val2_4_4_fu_695_p3;
wire   [0:0] tmp_31_fu_709_p3;
wire   [0:0] tmp_15_fu_721_p2;
wire   [0:0] p_41_i_i1_fu_727_p2;
wire   [0:0] deleted_zeros_1_fu_716_p3;
wire   [0:0] p_not_i_i1_fu_742_p2;
wire   [0:0] brmerge_i_i1_fu_748_p2;
wire   [0:0] deleted_ones_1_fu_732_p3;
wire   [0:0] tmp2_demorgan_fu_769_p2;
wire   [0:0] tmp2_fu_775_p2;
wire   [0:0] overflow_1_fu_758_p2;
wire   [0:0] tmp3_fu_792_p2;
wire   [0:0] underflow_1_not_fu_796_p2;
wire   [23:0] p_Val2_9_mux_fu_801_p3;
wire   [23:0] p_Val2_9_5_fu_807_p3;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_reg_ioackin_outDataLeft_V_ap_ack = 1'b0;
#0 ap_reg_ioackin_outDataRight_V_ap_ack = 1'b0;
end

biquadv2start_arrbkb #(
    .DataWidth( 27 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
array_r_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(array_r_address0),
    .ce0(array_r_ce0),
    .we0(array_r_we0),
    .d0(array_r_d0),
    .q0(array_r_q0),
    .address1(array_r_address1),
    .ce1(array_r_ce1),
    .we1(array_r_we1),
    .d1(array_r_d1),
    .q1(array_r_q1)
);

biquadv2start_biquadv2_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_BIQUADV2_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_BIQUADV2_DATA_WIDTH ))
biquadv2start_biquadv2_s_axi_U(
    .AWVALID(s_axi_biquadv2_AWVALID),
    .AWREADY(s_axi_biquadv2_AWREADY),
    .AWADDR(s_axi_biquadv2_AWADDR),
    .WVALID(s_axi_biquadv2_WVALID),
    .WREADY(s_axi_biquadv2_WREADY),
    .WDATA(s_axi_biquadv2_WDATA),
    .WSTRB(s_axi_biquadv2_WSTRB),
    .ARVALID(s_axi_biquadv2_ARVALID),
    .ARREADY(s_axi_biquadv2_ARREADY),
    .ARADDR(s_axi_biquadv2_ARADDR),
    .RVALID(s_axi_biquadv2_RVALID),
    .RREADY(s_axi_biquadv2_RREADY),
    .RDATA(s_axi_biquadv2_RDATA),
    .RRESP(s_axi_biquadv2_RRESP),
    .BVALID(s_axi_biquadv2_BVALID),
    .BREADY(s_axi_biquadv2_BREADY),
    .BRESP(s_axi_biquadv2_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .b0_a0_V(b0_a0_V),
    .b1_a0_V(b1_a0_V),
    .b2_a0_V(b2_a0_V),
    .a1_a0_V(a1_a0_V),
    .a2_a0_V(a2_a0_V),
    .inDataLeft_V(inDataLeft_V),
    .inDataRight_V(inDataRight_V)
);

biquadv2start_mulcud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 51 ))
biquadv2start_mulcud_U0(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_279_p0),
    .din1(grp_fu_279_p1),
    .ce(1'b1),
    .dout(grp_fu_279_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_outDataLeft_V_ap_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            if ((ap_block_state16_io == 1'b0)) begin
                ap_reg_ioackin_outDataLeft_V_ap_ack <= 1'b0;
            end else if ((1'b1 == outDataLeft_V_ap_ack)) begin
                ap_reg_ioackin_outDataLeft_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_outDataRight_V_ap_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            if ((ap_block_state16_io == 1'b0)) begin
                ap_reg_ioackin_outDataRight_V_ap_ack <= 1'b0;
            end else if ((1'b1 == outDataRight_V_ap_ack)) begin
                ap_reg_ioackin_outDataRight_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_Val2_5_reg_242 <= resultRight_V_fu_813_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_5_reg_242 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_Val2_s_reg_255 <= resultLeft_V_reg_1085;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_s_reg_255 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_s_reg_268 <= i_V_reg_901;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_s_reg_268 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        OP1_V_reg_936 <= OP1_V_fu_359_p1;
        tmp_26_reg_946 <= tmp_26_fu_367_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        Range1_all_ones_1_reg_1073 <= Range1_all_ones_1_fu_668_p2;
        Range1_all_zeros_1_reg_1080 <= Range1_all_zeros_1_fu_674_p2;
        Range2_all_ones_1_reg_1068 <= Range2_all_ones_1_fu_652_p2;
        brmerge40_demorgan_i_reg_1023 <= brmerge40_demorgan_i_fu_541_p2;
        brmerge_i_i_i_reg_1033 <= brmerge_i_i_i_fu_563_p2;
        carry_1_reg_1061 <= carry_1_fu_636_p2;
        newsignbit_1_reg_1055 <= p_Val2_9_fu_616_p2[32'd23];
        p_38_i_i_reg_1013 <= p_38_i_i_fu_515_p2;
        p_Val2_7_reg_1038 <= p_Val2_7_fu_581_p2;
        p_Val2_9_reg_1049 <= p_Val2_9_fu_616_p2;
        signbit_1_reg_1043 <= p_Val2_7_fu_581_p2[32'd50];
        tmp_9_reg_1018 <= tmp_9_fu_530_p2;
        underflow_reg_1028 <= underflow_fu_558_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Range1_all_ones_reg_996 <= Range1_all_ones_fu_474_p2;
        Range1_all_zeros_reg_1003 <= Range1_all_zeros_fu_480_p2;
        Range2_all_ones_reg_991 <= Range2_all_ones_fu_458_p2;
        carry_reg_984 <= carry_fu_442_p2;
        newsignbit_reg_978 <= p_Val2_4_fu_422_p2[32'd23];
        p_Val2_2_reg_961 <= p_Val2_2_fu_387_p2;
        p_Val2_4_reg_972 <= p_Val2_4_fu_422_p2;
        signbit_reg_966 <= p_Val2_2_fu_387_p2[32'd50];
        tmp_28_reg_1008 <= grp_fu_279_p2[32'd23];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        a1_a0_V_read_reg_878 <= a1_a0_V;
        a2_a0_V_read_reg_873 <= a2_a0_V;
        b2_a0_V_read_reg_883 <= b2_a0_V;
        inDataLeft_V_read_reg_868 <= inDataLeft_V;
        inDataRight_V_read_reg_863 <= inDataRight_V;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        array_load_4_reg_921 <= array_r_q1;
        tmp_20_reg_926 <= tmp_20_fu_345_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        brmerge40_demorgan_i_1_reg_1100 <= brmerge40_demorgan_i_1_fu_764_p2;
        brmerge_i_i_i1_reg_1110 <= brmerge_i_i_i1_fu_786_p2;
        p_38_i_i1_reg_1090 <= p_38_i_i1_fu_738_p2;
        resultLeft_V_reg_1085 <= resultLeft_V_fu_701_p3;
        tmp_16_reg_1095 <= tmp_16_fu_753_p2;
        underflow_1_reg_1105 <= underflow_1_fu_781_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_V_reg_901 <= i_V_fu_319_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        inDataLeft_V_trunc_reg_888[23 : 0] <= inDataLeft_V_trunc_fu_305_p1[23 : 0];
        inDataRight_V_trunc_reg_893[23 : 0] <= inDataRight_V_trunc_fu_309_p1[23 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state9))) begin
        reg_301 <= grp_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        tmp_17_reg_1125 <= tmp_17_fu_825_p1;
        tmp_4_reg_1120 <= tmp_4_fu_821_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        tmp_18_reg_1130 <= tmp_18_fu_838_p1;
        tmp_19_reg_1135 <= tmp_19_fu_842_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_22_reg_951 <= grp_fu_279_p2[32'd23];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd0))) begin
        tmp_3_cast_reg_906[2 : 0] <= tmp_3_cast_fu_330_p1[2 : 0];
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_outDataLeft_V_ap_ack)) begin
        ap_sig_ioackin_outDataLeft_V_ap_ack = outDataLeft_V_ap_ack;
    end else begin
        ap_sig_ioackin_outDataLeft_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_outDataRight_V_ap_ack)) begin
        ap_sig_ioackin_outDataRight_V_ap_ack = outDataRight_V_ap_ack;
    end else begin
        ap_sig_ioackin_outDataRight_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        array_r_address0 = 4'd12;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        array_r_address0 = 4'd14;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        array_r_address0 = 4'd7;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        array_r_address0 = 4'd9;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        array_r_address0 = 4'd13;
    end else if (((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd1))) begin
        array_r_address0 = 4'd6;
    end else if (((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd0))) begin
        array_r_address0 = addr5_cast_fu_340_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        array_r_address0 = 4'd10;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        array_r_address0 = 4'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        array_r_address0 = 4'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        array_r_address0 = 4'd0;
    end else begin
        array_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        array_r_address1 = 4'd13;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        array_r_address1 = 4'd6;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state17))) begin
        array_r_address1 = 4'd11;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        array_r_address1 = addr1_cast_fu_354_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd1)))) begin
        array_r_address1 = 4'd8;
    end else if (((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd0))) begin
        array_r_address1 = tmp_3_fu_325_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        array_r_address1 = 4'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        array_r_address1 = 4'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        array_r_address1 = 4'd1;
    end else begin
        array_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd0)) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state16) & (ap_block_state16_io == 1'b0)) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd1)) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state17))) begin
        array_r_ce0 = 1'b1;
    end else begin
        array_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd0)) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state16) & (ap_block_state16_io == 1'b0)) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd1)) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state17))) begin
        array_r_ce1 = 1'b1;
    end else begin
        array_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        array_r_d0 = samples_V_load_320_t_fu_859_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        array_r_d0 = samples_V_load_217_t_fu_850_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        array_r_d0 = samples_V_load_114_t_fu_846_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        array_r_d0 = samples_V_load11_tru_fu_829_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        array_r_d0 = inDataRight_V_trunc_fu_309_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        array_r_d0 = a2_a0_V_read_reg_873;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        array_r_d0 = b2_a0_V_read_reg_883;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        array_r_d0 = b0_a0_V;
    end else begin
        array_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        array_r_d1 = inDataRight_V_trunc_reg_893;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        array_r_d1 = p_Val2_5_trunc_fu_854_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        array_r_d1 = inDataLeft_V_trunc_reg_888;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        array_r_d1 = p_Val2_trunc_fu_833_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        array_r_d1 = inDataLeft_V_trunc_fu_305_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        array_r_d1 = a1_a0_V_read_reg_878;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        array_r_d1 = b1_a0_V;
    end else begin
        array_r_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state16) & (ap_block_state16_io == 1'b0)) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state17))) begin
        array_r_we0 = 1'b1;
    end else begin
        array_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state14) | ((1'b1 == ap_CS_fsm_state16) & (ap_block_state16_io == 1'b0)) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state17))) begin
        array_r_we1 = 1'b1;
    end else begin
        array_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_279_p0 = OP1_V_reg_936;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_279_p0 = OP1_V_fu_359_p1;
    end else begin
        grp_fu_279_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_279_p1 = OP2_V_1_fu_371_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_279_p1 = OP2_V_fu_363_p1;
    end else begin
        grp_fu_279_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (1'b0 == ap_reg_ioackin_outDataLeft_V_ap_ack))) begin
        outDataLeft_V_ap_vld = 1'b1;
    end else begin
        outDataLeft_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        outDataLeft_V_blk_n = outDataLeft_V_ap_ack;
    end else begin
        outDataLeft_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) & (1'b0 == ap_reg_ioackin_outDataRight_V_ap_ack))) begin
        outDataRight_V_ap_vld = 1'b1;
    end else begin
        outDataRight_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        outDataRight_V_blk_n = outDataRight_V_ap_ack;
    end else begin
        outDataRight_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (tmp_2_fu_313_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (ap_block_state16_io == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP1_V_fu_359_p1 = $signed(array_load_4_reg_921);

assign OP2_V_1_fu_371_p1 = $signed(tmp_26_reg_946);

assign OP2_V_fu_363_p1 = $signed(tmp_20_reg_926);

assign Range1_all_ones_1_fu_668_p2 = ((tmp_14_fu_658_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_474_p2 = ((tmp_7_fu_464_p4 == 3'd7) ? 1'b1 : 1'b0);

assign Range1_all_zeros_1_fu_674_p2 = ((tmp_14_fu_658_p4 == 3'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_480_p2 = ((tmp_7_fu_464_p4 == 3'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_1_fu_652_p2 = ((tmp_13_fu_642_p4 == 2'd3) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_458_p2 = ((tmp_6_fu_448_p4 == 2'd3) ? 1'b1 : 1'b0);

assign addr1_cast_fu_354_p1 = addr1_fu_349_p2;

assign addr1_fu_349_p2 = (4'd10 + tmp_3_cast_reg_906);

assign addr5_cast_fu_340_p1 = addr5_fu_334_p2;

assign addr5_fu_334_p2 = (4'd5 + tmp_3_cast_fu_330_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state16_io = ((1'b0 == ap_sig_ioackin_outDataLeft_V_ap_ack) | (1'b0 == ap_sig_ioackin_outDataRight_V_ap_ack));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign brmerge40_demorgan_i_1_fu_764_p2 = (newsignbit_1_reg_1055 & deleted_ones_1_fu_732_p3);

assign brmerge40_demorgan_i_fu_541_p2 = (newsignbit_reg_978 & deleted_ones_fu_509_p3);

assign brmerge_i_i1_fu_748_p2 = (newsignbit_1_reg_1055 | p_not_i_i1_fu_742_p2);

assign brmerge_i_i_fu_525_p2 = (newsignbit_reg_978 | p_not_i_i_fu_519_p2);

assign brmerge_i_i_i1_fu_786_p2 = (underflow_1_fu_781_p2 | overflow_1_fu_758_p2);

assign brmerge_i_i_i_fu_563_p2 = (underflow_fu_558_p2 | overflow_fu_535_p2);

assign carry_1_fu_636_p2 = (tmp_29_fu_608_p3 & tmp_12_fu_630_p2);

assign carry_fu_442_p2 = (tmp_23_fu_414_p3 & tmp_s_fu_436_p2);

assign deleted_ones_1_fu_732_p3 = ((carry_1_reg_1061[0:0] === 1'b1) ? p_41_i_i1_fu_727_p2 : Range1_all_ones_1_reg_1073);

assign deleted_ones_fu_509_p3 = ((carry_reg_984[0:0] === 1'b1) ? p_41_i_i_fu_504_p2 : Range1_all_ones_reg_996);

assign deleted_zeros_1_fu_716_p3 = ((carry_1_reg_1061[0:0] === 1'b1) ? Range1_all_ones_1_reg_1073 : Range1_all_zeros_1_reg_1080);

assign deleted_zeros_fu_493_p3 = ((carry_reg_984[0:0] === 1'b1) ? Range1_all_ones_reg_996 : Range1_all_zeros_reg_1003);

assign i_V_fu_319_p2 = (p_s_reg_268 + 3'd1);

assign inDataLeft_V_trunc_fu_305_p1 = inDataLeft_V_read_reg_868;

assign inDataRight_V_trunc_fu_309_p1 = inDataRight_V_read_reg_863;

assign newsignbit_1_fu_622_p3 = p_Val2_9_fu_616_p2[32'd23];

assign newsignbit_fu_428_p3 = p_Val2_4_fu_422_p2[32'd23];

assign outDataLeft_V = p_Val2_s_reg_255;

assign outDataRight_V = p_Val2_5_reg_242;

assign overflow_1_fu_758_p2 = (brmerge_i_i1_fu_748_p2 & tmp_16_fu_753_p2);

assign overflow_fu_535_p2 = (brmerge_i_i_fu_525_p2 & tmp_9_fu_530_p2);

assign p_38_i_i1_fu_738_p2 = (carry_1_reg_1061 & Range1_all_ones_1_reg_1073);

assign p_38_i_i_fu_515_p2 = (carry_reg_984 & Range1_all_ones_reg_996);

assign p_41_i_i1_fu_727_p2 = (Range2_all_ones_1_reg_1068 & tmp_15_fu_721_p2);

assign p_41_i_i_fu_504_p2 = (Range2_all_ones_reg_991 & tmp_1_fu_498_p2);

assign p_Val2_2_fu_387_p2 = ($signed(tmp_8_cast_fu_383_p1) + $signed(reg_301));

assign p_Val2_3_fu_401_p4 = {{p_Val2_2_fu_387_p2[47:24]}};

assign p_Val2_4_4_fu_695_p3 = ((underflow_reg_1028[0:0] === 1'b1) ? 24'd8388608 : p_Val2_4_reg_972);

assign p_Val2_4_fu_422_p2 = (p_Val2_3_fu_401_p4 + tmp_5_fu_411_p1);

assign p_Val2_4_mux_fu_689_p3 = ((brmerge_i_i_i_reg_1033[0:0] === 1'b1) ? 24'd8388607 : p_Val2_4_reg_972);

assign p_Val2_5_trunc_fu_854_p1 = p_Val2_5_reg_242;

assign p_Val2_7_fu_581_p2 = ($signed(tmp_13_cast_fu_577_p1) + $signed(reg_301));

assign p_Val2_8_fu_595_p4 = {{p_Val2_7_fu_581_p2[47:24]}};

assign p_Val2_9_5_fu_807_p3 = ((underflow_1_reg_1105[0:0] === 1'b1) ? 24'd8388608 : p_Val2_9_reg_1049);

assign p_Val2_9_fu_616_p2 = (p_Val2_8_fu_595_p4 + tmp_11_fu_605_p1);

assign p_Val2_9_mux_fu_801_p3 = ((brmerge_i_i_i1_reg_1110[0:0] === 1'b1) ? 24'd8388607 : p_Val2_9_reg_1049);

assign p_Val2_trunc_fu_833_p1 = p_Val2_s_reg_255;

assign p_not_i_i1_fu_742_p2 = (deleted_zeros_1_fu_716_p3 ^ 1'd1);

assign p_not_i_i_fu_519_p2 = (deleted_zeros_fu_493_p3 ^ 1'd1);

assign resultLeft_V_fu_701_p3 = ((underflow_not_fu_684_p2[0:0] === 1'b1) ? p_Val2_4_mux_fu_689_p3 : p_Val2_4_4_fu_695_p3);

assign resultRight_V_fu_813_p3 = ((underflow_1_not_fu_796_p2[0:0] === 1'b1) ? p_Val2_9_mux_fu_801_p3 : p_Val2_9_5_fu_807_p3);

assign samples_V_load11_tru_fu_829_p1 = tmp_4_reg_1120;

assign samples_V_load_114_t_fu_846_p1 = tmp_17_reg_1125;

assign samples_V_load_217_t_fu_850_p1 = tmp_18_reg_1130;

assign samples_V_load_320_t_fu_859_p1 = tmp_19_reg_1135;

assign tmp1_fu_680_p2 = (brmerge40_demorgan_i_reg_1023 | tmp_9_reg_1018);

assign tmp2_demorgan_fu_769_p2 = (p_38_i_i1_fu_738_p2 | brmerge40_demorgan_i_1_fu_764_p2);

assign tmp2_fu_775_p2 = (tmp2_demorgan_fu_769_p2 ^ 1'd1);

assign tmp3_fu_792_p2 = (brmerge40_demorgan_i_1_reg_1100 | tmp_16_reg_1095);

assign tmp_10_fu_569_p3 = {{p_Val2_5_reg_242}, {24'd0}};

assign tmp_11_fu_605_p1 = tmp_28_reg_1008;

assign tmp_12_fu_630_p2 = (newsignbit_1_fu_622_p3 ^ 1'd1);

assign tmp_13_cast_fu_577_p1 = $signed(tmp_10_fu_569_p3);

assign tmp_13_fu_642_p4 = {{p_Val2_7_fu_581_p2[50:49]}};

assign tmp_14_fu_658_p4 = {{p_Val2_7_fu_581_p2[50:48]}};

assign tmp_15_fu_721_p2 = (tmp_31_fu_709_p3 ^ 1'd1);

assign tmp_16_fu_753_p2 = (signbit_1_reg_1043 ^ 1'd1);

assign tmp_17_fu_825_p1 = array_r_q0[23:0];

assign tmp_18_fu_838_p1 = array_r_q0[23:0];

assign tmp_19_fu_842_p1 = array_r_q1[23:0];

assign tmp_1_fu_498_p2 = (tmp_25_fu_486_p3 ^ 1'd1);

assign tmp_20_fu_345_p1 = array_r_q0[23:0];

assign tmp_23_fu_414_p3 = p_Val2_2_fu_387_p2[32'd47];

assign tmp_25_fu_486_p3 = p_Val2_2_reg_961[32'd48];

assign tmp_26_fu_367_p1 = array_r_q1[23:0];

assign tmp_29_fu_608_p3 = p_Val2_7_fu_581_p2[32'd47];

assign tmp_2_fu_313_p2 = ((p_s_reg_268 == 3'd5) ? 1'b1 : 1'b0);

assign tmp_31_fu_709_p3 = p_Val2_7_reg_1038[32'd48];

assign tmp_3_cast_fu_330_p1 = p_s_reg_268;

assign tmp_3_fu_325_p1 = p_s_reg_268;

assign tmp_4_fu_821_p1 = array_r_q1[23:0];

assign tmp_5_fu_411_p1 = tmp_22_reg_951;

assign tmp_6_fu_448_p4 = {{p_Val2_2_fu_387_p2[50:49]}};

assign tmp_7_fu_464_p4 = {{p_Val2_2_fu_387_p2[50:48]}};

assign tmp_8_cast_fu_383_p1 = $signed(tmp_8_fu_375_p3);

assign tmp_8_fu_375_p3 = {{p_Val2_s_reg_255}, {24'd0}};

assign tmp_9_fu_530_p2 = (signbit_reg_966 ^ 1'd1);

assign tmp_demorgan_fu_546_p2 = (p_38_i_i_fu_515_p2 | brmerge40_demorgan_i_fu_541_p2);

assign tmp_fu_552_p2 = (tmp_demorgan_fu_546_p2 ^ 1'd1);

assign tmp_s_fu_436_p2 = (newsignbit_fu_428_p3 ^ 1'd1);

assign underflow_1_fu_781_p2 = (signbit_1_reg_1043 & tmp2_fu_775_p2);

assign underflow_1_not_fu_796_p2 = (tmp3_fu_792_p2 | p_38_i_i1_reg_1090);

assign underflow_fu_558_p2 = (signbit_reg_966 & tmp_fu_552_p2);

assign underflow_not_fu_684_p2 = (tmp1_fu_680_p2 | p_38_i_i_reg_1013);

always @ (posedge ap_clk) begin
    inDataLeft_V_trunc_reg_888[26:24] <= 3'b000;
    inDataRight_V_trunc_reg_893[26:24] <= 3'b000;
    tmp_3_cast_reg_906[3] <= 1'b0;
end

endmodule //biquadv2start
