// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Biquad,hls_ip_2017_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.912000,HLS_SYN_LAT=17,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=4,HLS_SYN_FF=507,HLS_SYN_LUT=275}" *)

module Biquad (
        inClk,
        inReset,
        inData,
        outData
);


input   inClk;
input   inReset;
input  [31:0] inData;
output  [31:0] outData;

reg[31:0] outData;

wire   [31:0] grp_Biquad_process_fu_58_outData;
wire    grp_Biquad_process_fu_58_outData_ap_vld;
wire   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;

Biquad_process grp_Biquad_process_fu_58(
    .ap_clk(inClk),
    .ap_rst(inReset),
    .inData(inData),
    .outData(grp_Biquad_process_fu_58_outData),
    .outData_ap_vld(grp_Biquad_process_fu_58_outData_ap_vld)
);

always @ (posedge inClk) begin
    if ((1'b1 == grp_Biquad_process_fu_58_outData_ap_vld)) begin
        outData <= grp_Biquad_process_fu_58_outData;
    end
end

assign ap_CS_fsm = 2'd0;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

endmodule //Biquad
