// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBIQUADV2COEFFS_H
#define XBIQUADV2COEFFS_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbiquadv2coeffs_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Coeffs_BaseAddress;
} XBiquadv2coeffs_Config;
#endif

typedef struct {
    u32 Coeffs_BaseAddress;
    u32 IsReady;
} XBiquadv2coeffs;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBiquadv2coeffs_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBiquadv2coeffs_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBiquadv2coeffs_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBiquadv2coeffs_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBiquadv2coeffs_Initialize(XBiquadv2coeffs *InstancePtr, u16 DeviceId);
XBiquadv2coeffs_Config* XBiquadv2coeffs_LookupConfig(u16 DeviceId);
int XBiquadv2coeffs_CfgInitialize(XBiquadv2coeffs *InstancePtr, XBiquadv2coeffs_Config *ConfigPtr);
#else
int XBiquadv2coeffs_Initialize(XBiquadv2coeffs *InstancePtr, const char* InstanceName);
int XBiquadv2coeffs_Release(XBiquadv2coeffs *InstancePtr);
#endif


void XBiquadv2coeffs_Set_in0b0_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data);
u32 XBiquadv2coeffs_Get_in0b0_a0_V(XBiquadv2coeffs *InstancePtr);
void XBiquadv2coeffs_Set_in0b1_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data);
u32 XBiquadv2coeffs_Get_in0b1_a0_V(XBiquadv2coeffs *InstancePtr);
void XBiquadv2coeffs_Set_in0b2_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data);
u32 XBiquadv2coeffs_Get_in0b2_a0_V(XBiquadv2coeffs *InstancePtr);
void XBiquadv2coeffs_Set_in0a1_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data);
u32 XBiquadv2coeffs_Get_in0a1_a0_V(XBiquadv2coeffs *InstancePtr);
void XBiquadv2coeffs_Set_in0a2_a0_V(XBiquadv2coeffs *InstancePtr, u32 Data);
u32 XBiquadv2coeffs_Get_in0a2_a0_V(XBiquadv2coeffs *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
