// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbiquadv2start.h"

extern XBiquadv2start_Config XBiquadv2start_ConfigTable[];

XBiquadv2start_Config *XBiquadv2start_LookupConfig(u16 DeviceId) {
	XBiquadv2start_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBIQUADV2START_NUM_INSTANCES; Index++) {
		if (XBiquadv2start_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBiquadv2start_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBiquadv2start_Initialize(XBiquadv2start *InstancePtr, u16 DeviceId) {
	XBiquadv2start_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBiquadv2start_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBiquadv2start_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

