// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "biquadv2end.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic biquadv2end::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic biquadv2end::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<17> biquadv2end::ap_ST_fsm_state1 = "1";
const sc_lv<17> biquadv2end::ap_ST_fsm_state2 = "10";
const sc_lv<17> biquadv2end::ap_ST_fsm_state3 = "100";
const sc_lv<17> biquadv2end::ap_ST_fsm_state4 = "1000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state5 = "10000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state6 = "100000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state7 = "1000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state8 = "10000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state9 = "100000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state10 = "1000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state11 = "10000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state12 = "100000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<17> biquadv2end::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<32> biquadv2end::ap_const_lv32_0 = "00000000000000000000000000000000";
const int biquadv2end::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> biquadv2end::ap_const_lv32_7 = "111";
const sc_lv<32> biquadv2end::ap_const_lv32_8 = "1000";
const sc_lv<32> biquadv2end::ap_const_lv32_3 = "11";
const sc_lv<32> biquadv2end::ap_const_lv32_4 = "100";
const sc_lv<1> biquadv2end::ap_const_lv1_0 = "0";
const sc_lv<32> biquadv2end::ap_const_lv32_5 = "101";
const sc_lv<32> biquadv2end::ap_const_lv32_6 = "110";
const sc_lv<32> biquadv2end::ap_const_lv32_9 = "1001";
const sc_lv<32> biquadv2end::ap_const_lv32_A = "1010";
const sc_lv<32> biquadv2end::ap_const_lv32_B = "1011";
const sc_lv<32> biquadv2end::ap_const_lv32_C = "1100";
const sc_lv<32> biquadv2end::ap_const_lv32_D = "1101";
const sc_lv<24> biquadv2end::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> biquadv2end::ap_const_lv3_0 = "000";
const sc_lv<32> biquadv2end::ap_const_lv32_F = "1111";
const sc_lv<4> biquadv2end::ap_const_lv4_0 = "0000";
const sc_lv<4> biquadv2end::ap_const_lv4_1 = "1";
const sc_lv<32> biquadv2end::ap_const_lv32_1 = "1";
const sc_lv<4> biquadv2end::ap_const_lv4_2 = "10";
const sc_lv<4> biquadv2end::ap_const_lv4_3 = "11";
const sc_lv<32> biquadv2end::ap_const_lv32_2 = "10";
const sc_lv<4> biquadv2end::ap_const_lv4_4 = "100";
const sc_lv<4> biquadv2end::ap_const_lv4_5 = "101";
const sc_lv<4> biquadv2end::ap_const_lv4_A = "1010";
const sc_lv<1> biquadv2end::ap_const_lv1_1 = "1";
const sc_lv<4> biquadv2end::ap_const_lv4_8 = "1000";
const sc_lv<4> biquadv2end::ap_const_lv4_6 = "110";
const sc_lv<4> biquadv2end::ap_const_lv4_D = "1101";
const sc_lv<4> biquadv2end::ap_const_lv4_B = "1011";
const sc_lv<4> biquadv2end::ap_const_lv4_9 = "1001";
const sc_lv<32> biquadv2end::ap_const_lv32_E = "1110";
const sc_lv<4> biquadv2end::ap_const_lv4_7 = "111";
const sc_lv<4> biquadv2end::ap_const_lv4_E = "1110";
const sc_lv<32> biquadv2end::ap_const_lv32_10 = "10000";
const sc_lv<4> biquadv2end::ap_const_lv4_C = "1100";
const sc_lv<32> biquadv2end::ap_const_lv32_17 = "10111";
const sc_lv<3> biquadv2end::ap_const_lv3_5 = "101";
const sc_lv<3> biquadv2end::ap_const_lv3_1 = "1";
const sc_lv<32> biquadv2end::ap_const_lv32_32 = "110010";
const sc_lv<32> biquadv2end::ap_const_lv32_18 = "11000";
const sc_lv<32> biquadv2end::ap_const_lv32_2F = "101111";
const sc_lv<32> biquadv2end::ap_const_lv32_31 = "110001";
const sc_lv<2> biquadv2end::ap_const_lv2_3 = "11";
const sc_lv<32> biquadv2end::ap_const_lv32_30 = "110000";
const sc_lv<3> biquadv2end::ap_const_lv3_7 = "111";
const sc_lv<24> biquadv2end::ap_const_lv24_7FFFFF = "11111111111111111111111";
const sc_lv<24> biquadv2end::ap_const_lv24_800000 = "100000000000000000000000";
const bool biquadv2end::ap_const_boolean_1 = true;

biquadv2end::biquadv2end(sc_module_name name) : sc_module(name), mVcdFile(0) {
    array_r_U = new biquadv2end_array_r("array_r_U");
    array_r_U->clk(ap_clk);
    array_r_U->reset(ap_rst_n_inv);
    array_r_U->address0(array_r_address0);
    array_r_U->ce0(array_r_ce0);
    array_r_U->we0(array_r_we0);
    array_r_U->d0(array_r_d0);
    array_r_U->q0(array_r_q0);
    array_r_U->address1(array_r_address1);
    array_r_U->ce1(array_r_ce1);
    array_r_U->we1(array_r_we1);
    array_r_U->d1(array_r_d1);
    array_r_U->q1(array_r_q1);
    biquadv2end_biquadv2_s_axi_U = new biquadv2end_biquadv2_s_axi<C_S_AXI_BIQUADV2_ADDR_WIDTH,C_S_AXI_BIQUADV2_DATA_WIDTH>("biquadv2end_biquadv2_s_axi_U");
    biquadv2end_biquadv2_s_axi_U->AWVALID(s_axi_biquadv2_AWVALID);
    biquadv2end_biquadv2_s_axi_U->AWREADY(s_axi_biquadv2_AWREADY);
    biquadv2end_biquadv2_s_axi_U->AWADDR(s_axi_biquadv2_AWADDR);
    biquadv2end_biquadv2_s_axi_U->WVALID(s_axi_biquadv2_WVALID);
    biquadv2end_biquadv2_s_axi_U->WREADY(s_axi_biquadv2_WREADY);
    biquadv2end_biquadv2_s_axi_U->WDATA(s_axi_biquadv2_WDATA);
    biquadv2end_biquadv2_s_axi_U->WSTRB(s_axi_biquadv2_WSTRB);
    biquadv2end_biquadv2_s_axi_U->ARVALID(s_axi_biquadv2_ARVALID);
    biquadv2end_biquadv2_s_axi_U->ARREADY(s_axi_biquadv2_ARREADY);
    biquadv2end_biquadv2_s_axi_U->ARADDR(s_axi_biquadv2_ARADDR);
    biquadv2end_biquadv2_s_axi_U->RVALID(s_axi_biquadv2_RVALID);
    biquadv2end_biquadv2_s_axi_U->RREADY(s_axi_biquadv2_RREADY);
    biquadv2end_biquadv2_s_axi_U->RDATA(s_axi_biquadv2_RDATA);
    biquadv2end_biquadv2_s_axi_U->RRESP(s_axi_biquadv2_RRESP);
    biquadv2end_biquadv2_s_axi_U->BVALID(s_axi_biquadv2_BVALID);
    biquadv2end_biquadv2_s_axi_U->BREADY(s_axi_biquadv2_BREADY);
    biquadv2end_biquadv2_s_axi_U->BRESP(s_axi_biquadv2_BRESP);
    biquadv2end_biquadv2_s_axi_U->ACLK(ap_clk);
    biquadv2end_biquadv2_s_axi_U->ARESET(ap_rst_n_inv);
    biquadv2end_biquadv2_s_axi_U->ACLK_EN(ap_var_for_const0);
    biquadv2end_biquadv2_s_axi_U->ap_start(ap_start);
    biquadv2end_biquadv2_s_axi_U->interrupt(interrupt);
    biquadv2end_biquadv2_s_axi_U->ap_ready(ap_ready);
    biquadv2end_biquadv2_s_axi_U->ap_done(ap_done);
    biquadv2end_biquadv2_s_axi_U->ap_idle(ap_idle);
    biquadv2end_biquadv2_s_axi_U->b0_a0_V(b0_a0_V);
    biquadv2end_biquadv2_s_axi_U->b1_a0_V(b1_a0_V);
    biquadv2end_biquadv2_s_axi_U->b2_a0_V(b2_a0_V);
    biquadv2end_biquadv2_s_axi_U->a1_a0_V(a1_a0_V);
    biquadv2end_biquadv2_s_axi_U->a2_a0_V(a2_a0_V);
    biquadv2end_biquadv2_s_axi_U->outDataLeft_V(p_Val2_s_reg_253);
    biquadv2end_biquadv2_s_axi_U->outDataLeft_V_ap_vld(outDataLeft_V_ap_vld);
    biquadv2end_biquadv2_s_axi_U->outDataRight_V(p_Val2_5_reg_240);
    biquadv2end_biquadv2_s_axi_U->outDataRight_V_ap_vld(outDataRight_V_ap_vld);
    biquadv2end_mul_2bkb_U0 = new biquadv2end_mul_2bkb<1,2,27,24,51>("biquadv2end_mul_2bkb_U0");
    biquadv2end_mul_2bkb_U0->clk(ap_clk);
    biquadv2end_mul_2bkb_U0->reset(ap_rst_n_inv);
    biquadv2end_mul_2bkb_U0->din0(grp_fu_277_p0);
    biquadv2end_mul_2bkb_U0->din1(grp_fu_277_p1);
    biquadv2end_mul_2bkb_U0->ce(ap_var_for_const0);
    biquadv2end_mul_2bkb_U0->dout(grp_fu_277_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_fu_357_p1);
    sensitive << ( array_load_4_reg_919 );

    SC_METHOD(thread_OP2_V_1_fu_369_p1);
    sensitive << ( tmp_26_reg_944 );

    SC_METHOD(thread_OP2_V_fu_361_p1);
    sensitive << ( tmp_20_reg_924 );

    SC_METHOD(thread_Range1_all_ones_1_fu_666_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_14_fu_656_p4 );

    SC_METHOD(thread_Range1_all_ones_fu_472_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_7_fu_462_p4 );

    SC_METHOD(thread_Range1_all_zeros_1_fu_672_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_14_fu_656_p4 );

    SC_METHOD(thread_Range1_all_zeros_fu_478_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_7_fu_462_p4 );

    SC_METHOD(thread_Range2_all_ones_1_fu_650_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_13_fu_640_p4 );

    SC_METHOD(thread_Range2_all_ones_fu_456_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_6_fu_446_p4 );

    SC_METHOD(thread_addr1_cast_fu_352_p1);
    sensitive << ( addr1_fu_347_p2 );

    SC_METHOD(thread_addr1_fu_347_p2);
    sensitive << ( tmp_3_cast_reg_904 );

    SC_METHOD(thread_addr5_cast_fu_338_p1);
    sensitive << ( addr5_fu_332_p2 );

    SC_METHOD(thread_addr5_fu_332_p2);
    sensitive << ( tmp_3_cast_fu_328_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_array_r_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_2_fu_311_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( addr5_cast_fu_338_p1 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_array_r_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_2_fu_311_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_3_fu_323_p1 );
    sensitive << ( addr1_cast_fu_352_p1 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_array_r_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_2_fu_311_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_array_r_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_2_fu_311_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_array_r_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( b0_a0_V );
    sensitive << ( a2_a0_V_read_reg_871 );
    sensitive << ( b2_a0_V_read_reg_881 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( inDataRight_V_trunc_fu_307_p1 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( samples_V_load11_tru_fu_827_p1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( samples_V_load_114_t_fu_844_p1 );
    sensitive << ( samples_V_load_217_t_fu_848_p1 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( samples_V_load_320_t_fu_857_p1 );

    SC_METHOD(thread_array_r_d1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( b1_a0_V );
    sensitive << ( a1_a0_V_read_reg_876 );
    sensitive << ( inDataLeft_V_trunc_fu_303_p1 );
    sensitive << ( inDataLeft_V_trunc_reg_886 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( inDataRight_V_trunc_reg_891 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( p_Val2_trunc_fu_831_p1 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( p_Val2_5_trunc_fu_852_p1 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_array_r_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_array_r_we1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_brmerge40_demorgan_i_1_fu_762_p2);
    sensitive << ( newsignbit_1_reg_1053 );
    sensitive << ( deleted_ones_1_fu_730_p3 );

    SC_METHOD(thread_brmerge40_demorgan_i_fu_539_p2);
    sensitive << ( newsignbit_reg_976 );
    sensitive << ( deleted_ones_fu_507_p3 );

    SC_METHOD(thread_brmerge_i_i1_fu_746_p2);
    sensitive << ( newsignbit_1_reg_1053 );
    sensitive << ( p_not_i_i1_fu_740_p2 );

    SC_METHOD(thread_brmerge_i_i_fu_523_p2);
    sensitive << ( newsignbit_reg_976 );
    sensitive << ( p_not_i_i_fu_517_p2 );

    SC_METHOD(thread_brmerge_i_i_i1_fu_784_p2);
    sensitive << ( underflow_1_fu_779_p2 );
    sensitive << ( overflow_1_fu_756_p2 );

    SC_METHOD(thread_brmerge_i_i_i_fu_561_p2);
    sensitive << ( underflow_fu_556_p2 );
    sensitive << ( overflow_fu_533_p2 );

    SC_METHOD(thread_carry_1_fu_634_p2);
    sensitive << ( tmp_29_fu_606_p3 );
    sensitive << ( tmp_12_fu_628_p2 );

    SC_METHOD(thread_carry_fu_440_p2);
    sensitive << ( tmp_23_fu_412_p3 );
    sensitive << ( tmp_s_fu_434_p2 );

    SC_METHOD(thread_deleted_ones_1_fu_730_p3);
    sensitive << ( carry_1_reg_1059 );
    sensitive << ( Range1_all_ones_1_reg_1071 );
    sensitive << ( p_41_i_i1_fu_725_p2 );

    SC_METHOD(thread_deleted_ones_fu_507_p3);
    sensitive << ( carry_reg_982 );
    sensitive << ( Range1_all_ones_reg_994 );
    sensitive << ( p_41_i_i_fu_502_p2 );

    SC_METHOD(thread_deleted_zeros_1_fu_714_p3);
    sensitive << ( carry_1_reg_1059 );
    sensitive << ( Range1_all_ones_1_reg_1071 );
    sensitive << ( Range1_all_zeros_1_reg_1078 );

    SC_METHOD(thread_deleted_zeros_fu_491_p3);
    sensitive << ( carry_reg_982 );
    sensitive << ( Range1_all_ones_reg_994 );
    sensitive << ( Range1_all_zeros_reg_1001 );

    SC_METHOD(thread_grp_fu_277_p0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( OP1_V_fu_357_p1 );
    sensitive << ( OP1_V_reg_934 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_277_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( OP2_V_fu_361_p1 );
    sensitive << ( OP2_V_1_fu_369_p1 );

    SC_METHOD(thread_i_V_fu_317_p2);
    sensitive << ( p_s_reg_266 );

    SC_METHOD(thread_inDataLeft_V_ap_ack);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );

    SC_METHOD(thread_inDataLeft_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );

    SC_METHOD(thread_inDataLeft_V_trunc_fu_303_p1);
    sensitive << ( inDataLeft_V_read_reg_866 );

    SC_METHOD(thread_inDataRight_V_ap_ack);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );

    SC_METHOD(thread_inDataRight_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataRight_V_ap_vld );

    SC_METHOD(thread_inDataRight_V_trunc_fu_307_p1);
    sensitive << ( inDataRight_V_read_reg_861 );

    SC_METHOD(thread_newsignbit_1_fu_620_p3);
    sensitive << ( p_Val2_9_fu_614_p2 );

    SC_METHOD(thread_newsignbit_fu_426_p3);
    sensitive << ( p_Val2_4_fu_420_p2 );

    SC_METHOD(thread_outDataLeft_V_ap_vld);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_outDataRight_V_ap_vld);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_overflow_1_fu_756_p2);
    sensitive << ( tmp_16_fu_751_p2 );
    sensitive << ( brmerge_i_i1_fu_746_p2 );

    SC_METHOD(thread_overflow_fu_533_p2);
    sensitive << ( tmp_9_fu_528_p2 );
    sensitive << ( brmerge_i_i_fu_523_p2 );

    SC_METHOD(thread_p_38_i_i1_fu_736_p2);
    sensitive << ( carry_1_reg_1059 );
    sensitive << ( Range1_all_ones_1_reg_1071 );

    SC_METHOD(thread_p_38_i_i_fu_513_p2);
    sensitive << ( carry_reg_982 );
    sensitive << ( Range1_all_ones_reg_994 );

    SC_METHOD(thread_p_41_i_i1_fu_725_p2);
    sensitive << ( Range2_all_ones_1_reg_1066 );
    sensitive << ( tmp_15_fu_719_p2 );

    SC_METHOD(thread_p_41_i_i_fu_502_p2);
    sensitive << ( Range2_all_ones_reg_989 );
    sensitive << ( tmp_1_fu_496_p2 );

    SC_METHOD(thread_p_Val2_2_fu_385_p2);
    sensitive << ( reg_299 );
    sensitive << ( tmp_8_cast_fu_381_p1 );

    SC_METHOD(thread_p_Val2_3_fu_399_p4);
    sensitive << ( p_Val2_2_fu_385_p2 );

    SC_METHOD(thread_p_Val2_4_4_fu_693_p3);
    sensitive << ( p_Val2_4_reg_970 );
    sensitive << ( underflow_reg_1026 );

    SC_METHOD(thread_p_Val2_4_fu_420_p2);
    sensitive << ( p_Val2_3_fu_399_p4 );
    sensitive << ( tmp_5_fu_409_p1 );

    SC_METHOD(thread_p_Val2_4_mux_fu_687_p3);
    sensitive << ( p_Val2_4_reg_970 );
    sensitive << ( brmerge_i_i_i_reg_1031 );

    SC_METHOD(thread_p_Val2_5_trunc_fu_852_p1);
    sensitive << ( p_Val2_5_reg_240 );

    SC_METHOD(thread_p_Val2_7_fu_579_p2);
    sensitive << ( reg_299 );
    sensitive << ( tmp_13_cast_fu_575_p1 );

    SC_METHOD(thread_p_Val2_8_fu_593_p4);
    sensitive << ( p_Val2_7_fu_579_p2 );

    SC_METHOD(thread_p_Val2_9_5_fu_805_p3);
    sensitive << ( p_Val2_9_reg_1047 );
    sensitive << ( underflow_1_reg_1103 );

    SC_METHOD(thread_p_Val2_9_fu_614_p2);
    sensitive << ( p_Val2_8_fu_593_p4 );
    sensitive << ( tmp_11_fu_603_p1 );

    SC_METHOD(thread_p_Val2_9_mux_fu_799_p3);
    sensitive << ( p_Val2_9_reg_1047 );
    sensitive << ( brmerge_i_i_i1_reg_1108 );

    SC_METHOD(thread_p_Val2_trunc_fu_831_p1);
    sensitive << ( p_Val2_s_reg_253 );

    SC_METHOD(thread_p_not_i_i1_fu_740_p2);
    sensitive << ( deleted_zeros_1_fu_714_p3 );

    SC_METHOD(thread_p_not_i_i_fu_517_p2);
    sensitive << ( deleted_zeros_fu_491_p3 );

    SC_METHOD(thread_resultLeft_V_fu_699_p3);
    sensitive << ( underflow_not_fu_682_p2 );
    sensitive << ( p_Val2_4_mux_fu_687_p3 );
    sensitive << ( p_Val2_4_4_fu_693_p3 );

    SC_METHOD(thread_resultRight_V_fu_811_p3);
    sensitive << ( underflow_1_not_fu_794_p2 );
    sensitive << ( p_Val2_9_mux_fu_799_p3 );
    sensitive << ( p_Val2_9_5_fu_805_p3 );

    SC_METHOD(thread_samples_V_load11_tru_fu_827_p1);
    sensitive << ( tmp_4_reg_1118 );

    SC_METHOD(thread_samples_V_load_114_t_fu_844_p1);
    sensitive << ( tmp_17_reg_1123 );

    SC_METHOD(thread_samples_V_load_217_t_fu_848_p1);
    sensitive << ( tmp_18_reg_1128 );

    SC_METHOD(thread_samples_V_load_320_t_fu_857_p1);
    sensitive << ( tmp_19_reg_1133 );

    SC_METHOD(thread_tmp1_fu_678_p2);
    sensitive << ( tmp_9_reg_1016 );
    sensitive << ( brmerge40_demorgan_i_reg_1021 );

    SC_METHOD(thread_tmp2_demorgan_fu_767_p2);
    sensitive << ( p_38_i_i1_fu_736_p2 );
    sensitive << ( brmerge40_demorgan_i_1_fu_762_p2 );

    SC_METHOD(thread_tmp2_fu_773_p2);
    sensitive << ( tmp2_demorgan_fu_767_p2 );

    SC_METHOD(thread_tmp3_fu_790_p2);
    sensitive << ( tmp_16_reg_1093 );
    sensitive << ( brmerge40_demorgan_i_1_reg_1098 );

    SC_METHOD(thread_tmp_10_fu_567_p3);
    sensitive << ( p_Val2_5_reg_240 );

    SC_METHOD(thread_tmp_11_fu_603_p1);
    sensitive << ( tmp_28_reg_1006 );

    SC_METHOD(thread_tmp_12_fu_628_p2);
    sensitive << ( newsignbit_1_fu_620_p3 );

    SC_METHOD(thread_tmp_13_cast_fu_575_p1);
    sensitive << ( tmp_10_fu_567_p3 );

    SC_METHOD(thread_tmp_13_fu_640_p4);
    sensitive << ( p_Val2_7_fu_579_p2 );

    SC_METHOD(thread_tmp_14_fu_656_p4);
    sensitive << ( p_Val2_7_fu_579_p2 );

    SC_METHOD(thread_tmp_15_fu_719_p2);
    sensitive << ( tmp_31_fu_707_p3 );

    SC_METHOD(thread_tmp_16_fu_751_p2);
    sensitive << ( signbit_1_reg_1041 );

    SC_METHOD(thread_tmp_17_fu_823_p1);
    sensitive << ( array_r_q0 );

    SC_METHOD(thread_tmp_18_fu_836_p1);
    sensitive << ( array_r_q0 );

    SC_METHOD(thread_tmp_19_fu_840_p1);
    sensitive << ( array_r_q1 );

    SC_METHOD(thread_tmp_1_fu_496_p2);
    sensitive << ( tmp_25_fu_484_p3 );

    SC_METHOD(thread_tmp_20_fu_343_p1);
    sensitive << ( array_r_q0 );

    SC_METHOD(thread_tmp_23_fu_412_p3);
    sensitive << ( p_Val2_2_fu_385_p2 );

    SC_METHOD(thread_tmp_25_fu_484_p3);
    sensitive << ( p_Val2_2_reg_959 );

    SC_METHOD(thread_tmp_26_fu_365_p1);
    sensitive << ( array_r_q1 );

    SC_METHOD(thread_tmp_29_fu_606_p3);
    sensitive << ( p_Val2_7_fu_579_p2 );

    SC_METHOD(thread_tmp_2_fu_311_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_s_reg_266 );

    SC_METHOD(thread_tmp_31_fu_707_p3);
    sensitive << ( p_Val2_7_reg_1036 );

    SC_METHOD(thread_tmp_3_cast_fu_328_p1);
    sensitive << ( p_s_reg_266 );

    SC_METHOD(thread_tmp_3_fu_323_p1);
    sensitive << ( p_s_reg_266 );

    SC_METHOD(thread_tmp_4_fu_819_p1);
    sensitive << ( array_r_q1 );

    SC_METHOD(thread_tmp_5_fu_409_p1);
    sensitive << ( tmp_22_reg_949 );

    SC_METHOD(thread_tmp_6_fu_446_p4);
    sensitive << ( p_Val2_2_fu_385_p2 );

    SC_METHOD(thread_tmp_7_fu_462_p4);
    sensitive << ( p_Val2_2_fu_385_p2 );

    SC_METHOD(thread_tmp_8_cast_fu_381_p1);
    sensitive << ( tmp_8_fu_373_p3 );

    SC_METHOD(thread_tmp_8_fu_373_p3);
    sensitive << ( p_Val2_s_reg_253 );

    SC_METHOD(thread_tmp_9_fu_528_p2);
    sensitive << ( signbit_reg_964 );

    SC_METHOD(thread_tmp_demorgan_fu_544_p2);
    sensitive << ( p_38_i_i_fu_513_p2 );
    sensitive << ( brmerge40_demorgan_i_fu_539_p2 );

    SC_METHOD(thread_tmp_fu_550_p2);
    sensitive << ( tmp_demorgan_fu_544_p2 );

    SC_METHOD(thread_tmp_s_fu_434_p2);
    sensitive << ( newsignbit_fu_426_p3 );

    SC_METHOD(thread_underflow_1_fu_779_p2);
    sensitive << ( signbit_1_reg_1041 );
    sensitive << ( tmp2_fu_773_p2 );

    SC_METHOD(thread_underflow_1_not_fu_794_p2);
    sensitive << ( p_38_i_i1_reg_1088 );
    sensitive << ( tmp3_fu_790_p2 );

    SC_METHOD(thread_underflow_fu_556_p2);
    sensitive << ( signbit_reg_964 );
    sensitive << ( tmp_fu_550_p2 );

    SC_METHOD(thread_underflow_not_fu_682_p2);
    sensitive << ( p_38_i_i_reg_1011 );
    sensitive << ( tmp1_fu_678_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( inDataLeft_V_ap_vld );
    sensitive << ( inDataRight_V_ap_vld );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_2_fu_311_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "biquadv2end_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, inDataLeft_V, "(port)inDataLeft_V");
    sc_trace(mVcdFile, inDataLeft_V_ap_vld, "(port)inDataLeft_V_ap_vld");
    sc_trace(mVcdFile, inDataLeft_V_ap_ack, "(port)inDataLeft_V_ap_ack");
    sc_trace(mVcdFile, inDataRight_V, "(port)inDataRight_V");
    sc_trace(mVcdFile, inDataRight_V_ap_vld, "(port)inDataRight_V_ap_vld");
    sc_trace(mVcdFile, inDataRight_V_ap_ack, "(port)inDataRight_V_ap_ack");
    sc_trace(mVcdFile, s_axi_biquadv2_AWVALID, "(port)s_axi_biquadv2_AWVALID");
    sc_trace(mVcdFile, s_axi_biquadv2_AWREADY, "(port)s_axi_biquadv2_AWREADY");
    sc_trace(mVcdFile, s_axi_biquadv2_AWADDR, "(port)s_axi_biquadv2_AWADDR");
    sc_trace(mVcdFile, s_axi_biquadv2_WVALID, "(port)s_axi_biquadv2_WVALID");
    sc_trace(mVcdFile, s_axi_biquadv2_WREADY, "(port)s_axi_biquadv2_WREADY");
    sc_trace(mVcdFile, s_axi_biquadv2_WDATA, "(port)s_axi_biquadv2_WDATA");
    sc_trace(mVcdFile, s_axi_biquadv2_WSTRB, "(port)s_axi_biquadv2_WSTRB");
    sc_trace(mVcdFile, s_axi_biquadv2_ARVALID, "(port)s_axi_biquadv2_ARVALID");
    sc_trace(mVcdFile, s_axi_biquadv2_ARREADY, "(port)s_axi_biquadv2_ARREADY");
    sc_trace(mVcdFile, s_axi_biquadv2_ARADDR, "(port)s_axi_biquadv2_ARADDR");
    sc_trace(mVcdFile, s_axi_biquadv2_RVALID, "(port)s_axi_biquadv2_RVALID");
    sc_trace(mVcdFile, s_axi_biquadv2_RREADY, "(port)s_axi_biquadv2_RREADY");
    sc_trace(mVcdFile, s_axi_biquadv2_RDATA, "(port)s_axi_biquadv2_RDATA");
    sc_trace(mVcdFile, s_axi_biquadv2_RRESP, "(port)s_axi_biquadv2_RRESP");
    sc_trace(mVcdFile, s_axi_biquadv2_BVALID, "(port)s_axi_biquadv2_BVALID");
    sc_trace(mVcdFile, s_axi_biquadv2_BREADY, "(port)s_axi_biquadv2_BREADY");
    sc_trace(mVcdFile, s_axi_biquadv2_BRESP, "(port)s_axi_biquadv2_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, b0_a0_V, "b0_a0_V");
    sc_trace(mVcdFile, b1_a0_V, "b1_a0_V");
    sc_trace(mVcdFile, b2_a0_V, "b2_a0_V");
    sc_trace(mVcdFile, a1_a0_V, "a1_a0_V");
    sc_trace(mVcdFile, a2_a0_V, "a2_a0_V");
    sc_trace(mVcdFile, outDataLeft_V_ap_vld, "outDataLeft_V_ap_vld");
    sc_trace(mVcdFile, outDataRight_V_ap_vld, "outDataRight_V_ap_vld");
    sc_trace(mVcdFile, array_r_address0, "array_r_address0");
    sc_trace(mVcdFile, array_r_ce0, "array_r_ce0");
    sc_trace(mVcdFile, array_r_we0, "array_r_we0");
    sc_trace(mVcdFile, array_r_d0, "array_r_d0");
    sc_trace(mVcdFile, array_r_q0, "array_r_q0");
    sc_trace(mVcdFile, array_r_address1, "array_r_address1");
    sc_trace(mVcdFile, array_r_ce1, "array_r_ce1");
    sc_trace(mVcdFile, array_r_we1, "array_r_we1");
    sc_trace(mVcdFile, array_r_d1, "array_r_d1");
    sc_trace(mVcdFile, array_r_q1, "array_r_q1");
    sc_trace(mVcdFile, inDataLeft_V_blk_n, "inDataLeft_V_blk_n");
    sc_trace(mVcdFile, inDataRight_V_blk_n, "inDataRight_V_blk_n");
    sc_trace(mVcdFile, grp_fu_277_p2, "grp_fu_277_p2");
    sc_trace(mVcdFile, reg_299, "reg_299");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, inDataRight_V_read_reg_861, "inDataRight_V_read_reg_861");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, inDataLeft_V_read_reg_866, "inDataLeft_V_read_reg_866");
    sc_trace(mVcdFile, a2_a0_V_read_reg_871, "a2_a0_V_read_reg_871");
    sc_trace(mVcdFile, a1_a0_V_read_reg_876, "a1_a0_V_read_reg_876");
    sc_trace(mVcdFile, b2_a0_V_read_reg_881, "b2_a0_V_read_reg_881");
    sc_trace(mVcdFile, inDataLeft_V_trunc_fu_303_p1, "inDataLeft_V_trunc_fu_303_p1");
    sc_trace(mVcdFile, inDataLeft_V_trunc_reg_886, "inDataLeft_V_trunc_reg_886");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, inDataRight_V_trunc_fu_307_p1, "inDataRight_V_trunc_fu_307_p1");
    sc_trace(mVcdFile, inDataRight_V_trunc_reg_891, "inDataRight_V_trunc_reg_891");
    sc_trace(mVcdFile, i_V_fu_317_p2, "i_V_fu_317_p2");
    sc_trace(mVcdFile, i_V_reg_899, "i_V_reg_899");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_3_cast_fu_328_p1, "tmp_3_cast_fu_328_p1");
    sc_trace(mVcdFile, tmp_3_cast_reg_904, "tmp_3_cast_reg_904");
    sc_trace(mVcdFile, tmp_2_fu_311_p2, "tmp_2_fu_311_p2");
    sc_trace(mVcdFile, array_load_4_reg_919, "array_load_4_reg_919");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_20_fu_343_p1, "tmp_20_fu_343_p1");
    sc_trace(mVcdFile, tmp_20_reg_924, "tmp_20_reg_924");
    sc_trace(mVcdFile, OP1_V_fu_357_p1, "OP1_V_fu_357_p1");
    sc_trace(mVcdFile, OP1_V_reg_934, "OP1_V_reg_934");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, OP2_V_fu_361_p1, "OP2_V_fu_361_p1");
    sc_trace(mVcdFile, tmp_26_fu_365_p1, "tmp_26_fu_365_p1");
    sc_trace(mVcdFile, tmp_26_reg_944, "tmp_26_reg_944");
    sc_trace(mVcdFile, tmp_22_reg_949, "tmp_22_reg_949");
    sc_trace(mVcdFile, OP2_V_1_fu_369_p1, "OP2_V_1_fu_369_p1");
    sc_trace(mVcdFile, p_Val2_2_fu_385_p2, "p_Val2_2_fu_385_p2");
    sc_trace(mVcdFile, p_Val2_2_reg_959, "p_Val2_2_reg_959");
    sc_trace(mVcdFile, signbit_reg_964, "signbit_reg_964");
    sc_trace(mVcdFile, p_Val2_4_fu_420_p2, "p_Val2_4_fu_420_p2");
    sc_trace(mVcdFile, p_Val2_4_reg_970, "p_Val2_4_reg_970");
    sc_trace(mVcdFile, newsignbit_fu_426_p3, "newsignbit_fu_426_p3");
    sc_trace(mVcdFile, newsignbit_reg_976, "newsignbit_reg_976");
    sc_trace(mVcdFile, carry_fu_440_p2, "carry_fu_440_p2");
    sc_trace(mVcdFile, carry_reg_982, "carry_reg_982");
    sc_trace(mVcdFile, Range2_all_ones_fu_456_p2, "Range2_all_ones_fu_456_p2");
    sc_trace(mVcdFile, Range2_all_ones_reg_989, "Range2_all_ones_reg_989");
    sc_trace(mVcdFile, Range1_all_ones_fu_472_p2, "Range1_all_ones_fu_472_p2");
    sc_trace(mVcdFile, Range1_all_ones_reg_994, "Range1_all_ones_reg_994");
    sc_trace(mVcdFile, Range1_all_zeros_fu_478_p2, "Range1_all_zeros_fu_478_p2");
    sc_trace(mVcdFile, Range1_all_zeros_reg_1001, "Range1_all_zeros_reg_1001");
    sc_trace(mVcdFile, tmp_28_reg_1006, "tmp_28_reg_1006");
    sc_trace(mVcdFile, p_38_i_i_fu_513_p2, "p_38_i_i_fu_513_p2");
    sc_trace(mVcdFile, p_38_i_i_reg_1011, "p_38_i_i_reg_1011");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_9_fu_528_p2, "tmp_9_fu_528_p2");
    sc_trace(mVcdFile, tmp_9_reg_1016, "tmp_9_reg_1016");
    sc_trace(mVcdFile, brmerge40_demorgan_i_fu_539_p2, "brmerge40_demorgan_i_fu_539_p2");
    sc_trace(mVcdFile, brmerge40_demorgan_i_reg_1021, "brmerge40_demorgan_i_reg_1021");
    sc_trace(mVcdFile, underflow_fu_556_p2, "underflow_fu_556_p2");
    sc_trace(mVcdFile, underflow_reg_1026, "underflow_reg_1026");
    sc_trace(mVcdFile, brmerge_i_i_i_fu_561_p2, "brmerge_i_i_i_fu_561_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_reg_1031, "brmerge_i_i_i_reg_1031");
    sc_trace(mVcdFile, p_Val2_7_fu_579_p2, "p_Val2_7_fu_579_p2");
    sc_trace(mVcdFile, p_Val2_7_reg_1036, "p_Val2_7_reg_1036");
    sc_trace(mVcdFile, signbit_1_reg_1041, "signbit_1_reg_1041");
    sc_trace(mVcdFile, p_Val2_9_fu_614_p2, "p_Val2_9_fu_614_p2");
    sc_trace(mVcdFile, p_Val2_9_reg_1047, "p_Val2_9_reg_1047");
    sc_trace(mVcdFile, newsignbit_1_fu_620_p3, "newsignbit_1_fu_620_p3");
    sc_trace(mVcdFile, newsignbit_1_reg_1053, "newsignbit_1_reg_1053");
    sc_trace(mVcdFile, carry_1_fu_634_p2, "carry_1_fu_634_p2");
    sc_trace(mVcdFile, carry_1_reg_1059, "carry_1_reg_1059");
    sc_trace(mVcdFile, Range2_all_ones_1_fu_650_p2, "Range2_all_ones_1_fu_650_p2");
    sc_trace(mVcdFile, Range2_all_ones_1_reg_1066, "Range2_all_ones_1_reg_1066");
    sc_trace(mVcdFile, Range1_all_ones_1_fu_666_p2, "Range1_all_ones_1_fu_666_p2");
    sc_trace(mVcdFile, Range1_all_ones_1_reg_1071, "Range1_all_ones_1_reg_1071");
    sc_trace(mVcdFile, Range1_all_zeros_1_fu_672_p2, "Range1_all_zeros_1_fu_672_p2");
    sc_trace(mVcdFile, Range1_all_zeros_1_reg_1078, "Range1_all_zeros_1_reg_1078");
    sc_trace(mVcdFile, resultLeft_V_fu_699_p3, "resultLeft_V_fu_699_p3");
    sc_trace(mVcdFile, resultLeft_V_reg_1083, "resultLeft_V_reg_1083");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_38_i_i1_fu_736_p2, "p_38_i_i1_fu_736_p2");
    sc_trace(mVcdFile, p_38_i_i1_reg_1088, "p_38_i_i1_reg_1088");
    sc_trace(mVcdFile, tmp_16_fu_751_p2, "tmp_16_fu_751_p2");
    sc_trace(mVcdFile, tmp_16_reg_1093, "tmp_16_reg_1093");
    sc_trace(mVcdFile, brmerge40_demorgan_i_1_fu_762_p2, "brmerge40_demorgan_i_1_fu_762_p2");
    sc_trace(mVcdFile, brmerge40_demorgan_i_1_reg_1098, "brmerge40_demorgan_i_1_reg_1098");
    sc_trace(mVcdFile, underflow_1_fu_779_p2, "underflow_1_fu_779_p2");
    sc_trace(mVcdFile, underflow_1_reg_1103, "underflow_1_reg_1103");
    sc_trace(mVcdFile, brmerge_i_i_i1_fu_784_p2, "brmerge_i_i_i1_fu_784_p2");
    sc_trace(mVcdFile, brmerge_i_i_i1_reg_1108, "brmerge_i_i_i1_reg_1108");
    sc_trace(mVcdFile, resultRight_V_fu_811_p3, "resultRight_V_fu_811_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, tmp_4_fu_819_p1, "tmp_4_fu_819_p1");
    sc_trace(mVcdFile, tmp_4_reg_1118, "tmp_4_reg_1118");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, tmp_17_fu_823_p1, "tmp_17_fu_823_p1");
    sc_trace(mVcdFile, tmp_17_reg_1123, "tmp_17_reg_1123");
    sc_trace(mVcdFile, tmp_18_fu_836_p1, "tmp_18_fu_836_p1");
    sc_trace(mVcdFile, tmp_18_reg_1128, "tmp_18_reg_1128");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_19_fu_840_p1, "tmp_19_fu_840_p1");
    sc_trace(mVcdFile, tmp_19_reg_1133, "tmp_19_reg_1133");
    sc_trace(mVcdFile, p_Val2_5_reg_240, "p_Val2_5_reg_240");
    sc_trace(mVcdFile, p_Val2_s_reg_253, "p_Val2_s_reg_253");
    sc_trace(mVcdFile, p_s_reg_266, "p_s_reg_266");
    sc_trace(mVcdFile, tmp_3_fu_323_p1, "tmp_3_fu_323_p1");
    sc_trace(mVcdFile, addr5_cast_fu_338_p1, "addr5_cast_fu_338_p1");
    sc_trace(mVcdFile, addr1_cast_fu_352_p1, "addr1_cast_fu_352_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, samples_V_load11_tru_fu_827_p1, "samples_V_load11_tru_fu_827_p1");
    sc_trace(mVcdFile, p_Val2_trunc_fu_831_p1, "p_Val2_trunc_fu_831_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, samples_V_load_114_t_fu_844_p1, "samples_V_load_114_t_fu_844_p1");
    sc_trace(mVcdFile, samples_V_load_217_t_fu_848_p1, "samples_V_load_217_t_fu_848_p1");
    sc_trace(mVcdFile, p_Val2_5_trunc_fu_852_p1, "p_Val2_5_trunc_fu_852_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, samples_V_load_320_t_fu_857_p1, "samples_V_load_320_t_fu_857_p1");
    sc_trace(mVcdFile, grp_fu_277_p0, "grp_fu_277_p0");
    sc_trace(mVcdFile, grp_fu_277_p1, "grp_fu_277_p1");
    sc_trace(mVcdFile, addr5_fu_332_p2, "addr5_fu_332_p2");
    sc_trace(mVcdFile, addr1_fu_347_p2, "addr1_fu_347_p2");
    sc_trace(mVcdFile, tmp_8_fu_373_p3, "tmp_8_fu_373_p3");
    sc_trace(mVcdFile, tmp_8_cast_fu_381_p1, "tmp_8_cast_fu_381_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_399_p4, "p_Val2_3_fu_399_p4");
    sc_trace(mVcdFile, tmp_5_fu_409_p1, "tmp_5_fu_409_p1");
    sc_trace(mVcdFile, tmp_23_fu_412_p3, "tmp_23_fu_412_p3");
    sc_trace(mVcdFile, tmp_s_fu_434_p2, "tmp_s_fu_434_p2");
    sc_trace(mVcdFile, tmp_6_fu_446_p4, "tmp_6_fu_446_p4");
    sc_trace(mVcdFile, tmp_7_fu_462_p4, "tmp_7_fu_462_p4");
    sc_trace(mVcdFile, tmp_25_fu_484_p3, "tmp_25_fu_484_p3");
    sc_trace(mVcdFile, tmp_1_fu_496_p2, "tmp_1_fu_496_p2");
    sc_trace(mVcdFile, p_41_i_i_fu_502_p2, "p_41_i_i_fu_502_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_491_p3, "deleted_zeros_fu_491_p3");
    sc_trace(mVcdFile, p_not_i_i_fu_517_p2, "p_not_i_i_fu_517_p2");
    sc_trace(mVcdFile, brmerge_i_i_fu_523_p2, "brmerge_i_i_fu_523_p2");
    sc_trace(mVcdFile, deleted_ones_fu_507_p3, "deleted_ones_fu_507_p3");
    sc_trace(mVcdFile, tmp_demorgan_fu_544_p2, "tmp_demorgan_fu_544_p2");
    sc_trace(mVcdFile, tmp_fu_550_p2, "tmp_fu_550_p2");
    sc_trace(mVcdFile, overflow_fu_533_p2, "overflow_fu_533_p2");
    sc_trace(mVcdFile, tmp_10_fu_567_p3, "tmp_10_fu_567_p3");
    sc_trace(mVcdFile, tmp_13_cast_fu_575_p1, "tmp_13_cast_fu_575_p1");
    sc_trace(mVcdFile, p_Val2_8_fu_593_p4, "p_Val2_8_fu_593_p4");
    sc_trace(mVcdFile, tmp_11_fu_603_p1, "tmp_11_fu_603_p1");
    sc_trace(mVcdFile, tmp_29_fu_606_p3, "tmp_29_fu_606_p3");
    sc_trace(mVcdFile, tmp_12_fu_628_p2, "tmp_12_fu_628_p2");
    sc_trace(mVcdFile, tmp_13_fu_640_p4, "tmp_13_fu_640_p4");
    sc_trace(mVcdFile, tmp_14_fu_656_p4, "tmp_14_fu_656_p4");
    sc_trace(mVcdFile, tmp1_fu_678_p2, "tmp1_fu_678_p2");
    sc_trace(mVcdFile, underflow_not_fu_682_p2, "underflow_not_fu_682_p2");
    sc_trace(mVcdFile, p_Val2_4_mux_fu_687_p3, "p_Val2_4_mux_fu_687_p3");
    sc_trace(mVcdFile, p_Val2_4_4_fu_693_p3, "p_Val2_4_4_fu_693_p3");
    sc_trace(mVcdFile, tmp_31_fu_707_p3, "tmp_31_fu_707_p3");
    sc_trace(mVcdFile, tmp_15_fu_719_p2, "tmp_15_fu_719_p2");
    sc_trace(mVcdFile, p_41_i_i1_fu_725_p2, "p_41_i_i1_fu_725_p2");
    sc_trace(mVcdFile, deleted_zeros_1_fu_714_p3, "deleted_zeros_1_fu_714_p3");
    sc_trace(mVcdFile, p_not_i_i1_fu_740_p2, "p_not_i_i1_fu_740_p2");
    sc_trace(mVcdFile, brmerge_i_i1_fu_746_p2, "brmerge_i_i1_fu_746_p2");
    sc_trace(mVcdFile, deleted_ones_1_fu_730_p3, "deleted_ones_1_fu_730_p3");
    sc_trace(mVcdFile, tmp2_demorgan_fu_767_p2, "tmp2_demorgan_fu_767_p2");
    sc_trace(mVcdFile, tmp2_fu_773_p2, "tmp2_fu_773_p2");
    sc_trace(mVcdFile, overflow_1_fu_756_p2, "overflow_1_fu_756_p2");
    sc_trace(mVcdFile, tmp3_fu_790_p2, "tmp3_fu_790_p2");
    sc_trace(mVcdFile, underflow_1_not_fu_794_p2, "underflow_1_not_fu_794_p2");
    sc_trace(mVcdFile, p_Val2_9_mux_fu_799_p3, "p_Val2_9_mux_fu_799_p3");
    sc_trace(mVcdFile, p_Val2_9_5_fu_805_p3, "p_Val2_9_5_fu_805_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("biquadv2end.hdltvin.dat");
    mHdltvoutHandle.open("biquadv2end.hdltvout.dat");
}

biquadv2end::~biquadv2end() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete array_r_U;
    delete biquadv2end_biquadv2_s_axi_U;
    delete biquadv2end_mul_2bkb_U0;
}

void biquadv2end::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void biquadv2end::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_Val2_5_reg_240 = resultRight_V_fu_811_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_5_reg_240 = ap_const_lv24_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_Val2_s_reg_253 = resultLeft_V_reg_1083.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_s_reg_253 = ap_const_lv24_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_s_reg_266 = i_V_reg_899.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_s_reg_266 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        OP1_V_reg_934 = OP1_V_fu_357_p1.read();
        tmp_26_reg_944 = tmp_26_fu_365_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        Range1_all_ones_1_reg_1071 = Range1_all_ones_1_fu_666_p2.read();
        Range1_all_zeros_1_reg_1078 = Range1_all_zeros_1_fu_672_p2.read();
        Range2_all_ones_1_reg_1066 = Range2_all_ones_1_fu_650_p2.read();
        brmerge40_demorgan_i_reg_1021 = brmerge40_demorgan_i_fu_539_p2.read();
        brmerge_i_i_i_reg_1031 = brmerge_i_i_i_fu_561_p2.read();
        carry_1_reg_1059 = carry_1_fu_634_p2.read();
        newsignbit_1_reg_1053 = p_Val2_9_fu_614_p2.read().range(23, 23);
        p_38_i_i_reg_1011 = p_38_i_i_fu_513_p2.read();
        p_Val2_7_reg_1036 = p_Val2_7_fu_579_p2.read();
        p_Val2_9_reg_1047 = p_Val2_9_fu_614_p2.read();
        signbit_1_reg_1041 = p_Val2_7_fu_579_p2.read().range(50, 50);
        tmp_9_reg_1016 = tmp_9_fu_528_p2.read();
        underflow_reg_1026 = underflow_fu_556_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Range1_all_ones_reg_994 = Range1_all_ones_fu_472_p2.read();
        Range1_all_zeros_reg_1001 = Range1_all_zeros_fu_478_p2.read();
        Range2_all_ones_reg_989 = Range2_all_ones_fu_456_p2.read();
        carry_reg_982 = carry_fu_440_p2.read();
        newsignbit_reg_976 = p_Val2_4_fu_420_p2.read().range(23, 23);
        p_Val2_2_reg_959 = p_Val2_2_fu_385_p2.read();
        p_Val2_4_reg_970 = p_Val2_4_fu_420_p2.read();
        signbit_reg_964 = p_Val2_2_fu_385_p2.read().range(50, 50);
        tmp_28_reg_1006 = grp_fu_277_p2.read().range(23, 23);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read())))) {
        a1_a0_V_read_reg_876 = a1_a0_V.read();
        a2_a0_V_read_reg_871 = a2_a0_V.read();
        b2_a0_V_read_reg_881 = b2_a0_V.read();
        inDataLeft_V_read_reg_866 = inDataLeft_V.read();
        inDataRight_V_read_reg_861 = inDataRight_V.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        array_load_4_reg_919 = array_r_q1.read();
        tmp_20_reg_924 = tmp_20_fu_343_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        brmerge40_demorgan_i_1_reg_1098 = brmerge40_demorgan_i_1_fu_762_p2.read();
        brmerge_i_i_i1_reg_1108 = brmerge_i_i_i1_fu_784_p2.read();
        p_38_i_i1_reg_1088 = p_38_i_i1_fu_736_p2.read();
        resultLeft_V_reg_1083 = resultLeft_V_fu_699_p3.read();
        tmp_16_reg_1093 = tmp_16_fu_751_p2.read();
        underflow_1_reg_1103 = underflow_1_fu_779_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_V_reg_899 = i_V_fu_317_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        inDataLeft_V_trunc_reg_886 = inDataLeft_V_trunc_fu_303_p1.read();
        inDataRight_V_trunc_reg_891 = inDataRight_V_trunc_fu_307_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        reg_299 = grp_fu_277_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_17_reg_1123 = tmp_17_fu_823_p1.read();
        tmp_4_reg_1118 = tmp_4_fu_819_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        tmp_18_reg_1128 = tmp_18_fu_836_p1.read();
        tmp_19_reg_1133 = tmp_19_fu_840_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_22_reg_949 = grp_fu_277_p2.read().range(23, 23);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_0))) {
        tmp_3_cast_reg_904 = tmp_3_cast_fu_328_p1.read();
    }
}

void biquadv2end::thread_OP1_V_fu_357_p1() {
    OP1_V_fu_357_p1 = esl_sext<51,27>(array_load_4_reg_919.read());
}

void biquadv2end::thread_OP2_V_1_fu_369_p1() {
    OP2_V_1_fu_369_p1 = esl_sext<51,24>(tmp_26_reg_944.read());
}

void biquadv2end::thread_OP2_V_fu_361_p1() {
    OP2_V_fu_361_p1 = esl_sext<51,24>(tmp_20_reg_924.read());
}

void biquadv2end::thread_Range1_all_ones_1_fu_666_p2() {
    Range1_all_ones_1_fu_666_p2 = (!tmp_14_fu_656_p4.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(tmp_14_fu_656_p4.read() == ap_const_lv3_7);
}

void biquadv2end::thread_Range1_all_ones_fu_472_p2() {
    Range1_all_ones_fu_472_p2 = (!tmp_7_fu_462_p4.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<1>(): sc_lv<1>(tmp_7_fu_462_p4.read() == ap_const_lv3_7);
}

void biquadv2end::thread_Range1_all_zeros_1_fu_672_p2() {
    Range1_all_zeros_1_fu_672_p2 = (!tmp_14_fu_656_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_14_fu_656_p4.read() == ap_const_lv3_0);
}

void biquadv2end::thread_Range1_all_zeros_fu_478_p2() {
    Range1_all_zeros_fu_478_p2 = (!tmp_7_fu_462_p4.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_7_fu_462_p4.read() == ap_const_lv3_0);
}

void biquadv2end::thread_Range2_all_ones_1_fu_650_p2() {
    Range2_all_ones_1_fu_650_p2 = (!tmp_13_fu_640_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_13_fu_640_p4.read() == ap_const_lv2_3);
}

void biquadv2end::thread_Range2_all_ones_fu_456_p2() {
    Range2_all_ones_fu_456_p2 = (!tmp_6_fu_446_p4.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_6_fu_446_p4.read() == ap_const_lv2_3);
}

void biquadv2end::thread_addr1_cast_fu_352_p1() {
    addr1_cast_fu_352_p1 = esl_zext<32,4>(addr1_fu_347_p2.read());
}

void biquadv2end::thread_addr1_fu_347_p2() {
    addr1_fu_347_p2 = (!ap_const_lv4_A.is_01() || !tmp_3_cast_reg_904.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_A) + sc_biguint<4>(tmp_3_cast_reg_904.read()));
}

void biquadv2end::thread_addr5_cast_fu_338_p1() {
    addr5_cast_fu_338_p1 = esl_zext<32,4>(addr5_fu_332_p2.read());
}

void biquadv2end::thread_addr5_fu_332_p2() {
    addr5_fu_332_p2 = (!ap_const_lv4_5.is_01() || !tmp_3_cast_fu_328_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_5) + sc_biguint<4>(tmp_3_cast_fu_328_p1.read()));
}

void biquadv2end::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void biquadv2end::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void biquadv2end::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void biquadv2end::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void biquadv2end::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void biquadv2end::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void biquadv2end::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void biquadv2end::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void biquadv2end::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void biquadv2end::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void biquadv2end::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void biquadv2end::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void biquadv2end::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void biquadv2end::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void biquadv2end::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void biquadv2end::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void biquadv2end::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void biquadv2end::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read()));
}

void biquadv2end::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void biquadv2end::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void biquadv2end::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void biquadv2end::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void biquadv2end::thread_array_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        array_r_address0 = ap_const_lv4_C;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        array_r_address0 = ap_const_lv4_E;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        array_r_address0 = ap_const_lv4_7;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        array_r_address0 = ap_const_lv4_9;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        array_r_address0 = ap_const_lv4_D;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_1))) {
        array_r_address0 = ap_const_lv4_6;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_0))) {
        array_r_address0 =  (sc_lv<4>) (addr5_cast_fu_338_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        array_r_address0 = ap_const_lv4_A;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        array_r_address0 = ap_const_lv4_4;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_r_address0 = ap_const_lv4_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        array_r_address0 = ap_const_lv4_0;
    } else {
        array_r_address0 = "XXXX";
    }
}

void biquadv2end::thread_array_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        array_r_address1 = ap_const_lv4_D;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        array_r_address1 = ap_const_lv4_6;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        array_r_address1 = ap_const_lv4_B;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        array_r_address1 =  (sc_lv<4>) (addr1_cast_fu_352_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                 esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_1)))) {
        array_r_address1 = ap_const_lv4_8;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_0))) {
        array_r_address1 =  (sc_lv<4>) (tmp_3_fu_323_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        array_r_address1 = ap_const_lv4_5;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_r_address1 = ap_const_lv4_3;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        array_r_address1 = ap_const_lv4_1;
    } else {
        array_r_address1 = "XXXX";
    }
}

void biquadv2end::thread_array_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        array_r_ce0 = ap_const_logic_1;
    } else {
        array_r_ce0 = ap_const_logic_0;
    }
}

void biquadv2end::thread_array_r_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        array_r_ce1 = ap_const_logic_1;
    } else {
        array_r_ce1 = ap_const_logic_0;
    }
}

void biquadv2end::thread_array_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        array_r_d0 = samples_V_load_320_t_fu_857_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        array_r_d0 = samples_V_load_217_t_fu_848_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        array_r_d0 = samples_V_load_114_t_fu_844_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        array_r_d0 = samples_V_load11_tru_fu_827_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        array_r_d0 = inDataRight_V_trunc_fu_307_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        array_r_d0 = a2_a0_V_read_reg_871.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_r_d0 = b2_a0_V_read_reg_881.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        array_r_d0 = b0_a0_V.read();
    } else {
        array_r_d0 =  (sc_lv<27>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void biquadv2end::thread_array_r_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        array_r_d1 = inDataRight_V_trunc_reg_891.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        array_r_d1 = p_Val2_5_trunc_fu_852_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        array_r_d1 = inDataLeft_V_trunc_reg_886.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        array_r_d1 = p_Val2_trunc_fu_831_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        array_r_d1 = inDataLeft_V_trunc_fu_303_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_r_d1 = a1_a0_V_read_reg_876.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        array_r_d1 = b1_a0_V.read();
    } else {
        array_r_d1 =  (sc_lv<27>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void biquadv2end::thread_array_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        array_r_we0 = ap_const_logic_1;
    } else {
        array_r_we0 = ap_const_logic_0;
    }
}

void biquadv2end::thread_array_r_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        array_r_we1 = ap_const_logic_1;
    } else {
        array_r_we1 = ap_const_logic_0;
    }
}

void biquadv2end::thread_brmerge40_demorgan_i_1_fu_762_p2() {
    brmerge40_demorgan_i_1_fu_762_p2 = (newsignbit_1_reg_1053.read() & deleted_ones_1_fu_730_p3.read());
}

void biquadv2end::thread_brmerge40_demorgan_i_fu_539_p2() {
    brmerge40_demorgan_i_fu_539_p2 = (newsignbit_reg_976.read() & deleted_ones_fu_507_p3.read());
}

void biquadv2end::thread_brmerge_i_i1_fu_746_p2() {
    brmerge_i_i1_fu_746_p2 = (newsignbit_1_reg_1053.read() | p_not_i_i1_fu_740_p2.read());
}

void biquadv2end::thread_brmerge_i_i_fu_523_p2() {
    brmerge_i_i_fu_523_p2 = (newsignbit_reg_976.read() | p_not_i_i_fu_517_p2.read());
}

void biquadv2end::thread_brmerge_i_i_i1_fu_784_p2() {
    brmerge_i_i_i1_fu_784_p2 = (underflow_1_fu_779_p2.read() | overflow_1_fu_756_p2.read());
}

void biquadv2end::thread_brmerge_i_i_i_fu_561_p2() {
    brmerge_i_i_i_fu_561_p2 = (underflow_fu_556_p2.read() | overflow_fu_533_p2.read());
}

void biquadv2end::thread_carry_1_fu_634_p2() {
    carry_1_fu_634_p2 = (tmp_29_fu_606_p3.read() & tmp_12_fu_628_p2.read());
}

void biquadv2end::thread_carry_fu_440_p2() {
    carry_fu_440_p2 = (tmp_23_fu_412_p3.read() & tmp_s_fu_434_p2.read());
}

void biquadv2end::thread_deleted_ones_1_fu_730_p3() {
    deleted_ones_1_fu_730_p3 = (!carry_1_reg_1059.read()[0].is_01())? sc_lv<1>(): ((carry_1_reg_1059.read()[0].to_bool())? p_41_i_i1_fu_725_p2.read(): Range1_all_ones_1_reg_1071.read());
}

void biquadv2end::thread_deleted_ones_fu_507_p3() {
    deleted_ones_fu_507_p3 = (!carry_reg_982.read()[0].is_01())? sc_lv<1>(): ((carry_reg_982.read()[0].to_bool())? p_41_i_i_fu_502_p2.read(): Range1_all_ones_reg_994.read());
}

void biquadv2end::thread_deleted_zeros_1_fu_714_p3() {
    deleted_zeros_1_fu_714_p3 = (!carry_1_reg_1059.read()[0].is_01())? sc_lv<1>(): ((carry_1_reg_1059.read()[0].to_bool())? Range1_all_ones_1_reg_1071.read(): Range1_all_zeros_1_reg_1078.read());
}

void biquadv2end::thread_deleted_zeros_fu_491_p3() {
    deleted_zeros_fu_491_p3 = (!carry_reg_982.read()[0].is_01())? sc_lv<1>(): ((carry_reg_982.read()[0].to_bool())? Range1_all_ones_reg_994.read(): Range1_all_zeros_reg_1001.read());
}

void biquadv2end::thread_grp_fu_277_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        grp_fu_277_p0 =  (sc_lv<27>) (OP1_V_reg_934.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_277_p0 =  (sc_lv<27>) (OP1_V_fu_357_p1.read());
    } else {
        grp_fu_277_p0 =  (sc_lv<27>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void biquadv2end::thread_grp_fu_277_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        grp_fu_277_p1 =  (sc_lv<24>) (OP2_V_1_fu_369_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        grp_fu_277_p1 =  (sc_lv<24>) (OP2_V_fu_361_p1.read());
    } else {
        grp_fu_277_p1 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void biquadv2end::thread_i_V_fu_317_p2() {
    i_V_fu_317_p2 = (!p_s_reg_266.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_s_reg_266.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void biquadv2end::thread_inDataLeft_V_ap_ack() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read())))) {
        inDataLeft_V_ap_ack = ap_const_logic_1;
    } else {
        inDataLeft_V_ap_ack = ap_const_logic_0;
    }
}

void biquadv2end::thread_inDataLeft_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        inDataLeft_V_blk_n = inDataLeft_V_ap_vld.read();
    } else {
        inDataLeft_V_blk_n = ap_const_logic_1;
    }
}

void biquadv2end::thread_inDataLeft_V_trunc_fu_303_p1() {
    inDataLeft_V_trunc_fu_303_p1 = esl_zext<27,24>(inDataLeft_V_read_reg_866.read());
}

void biquadv2end::thread_inDataRight_V_ap_ack() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read())))) {
        inDataRight_V_ap_ack = ap_const_logic_1;
    } else {
        inDataRight_V_ap_ack = ap_const_logic_0;
    }
}

void biquadv2end::thread_inDataRight_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        inDataRight_V_blk_n = inDataRight_V_ap_vld.read();
    } else {
        inDataRight_V_blk_n = ap_const_logic_1;
    }
}

void biquadv2end::thread_inDataRight_V_trunc_fu_307_p1() {
    inDataRight_V_trunc_fu_307_p1 = esl_zext<27,24>(inDataRight_V_read_reg_861.read());
}

void biquadv2end::thread_newsignbit_1_fu_620_p3() {
    newsignbit_1_fu_620_p3 = p_Val2_9_fu_614_p2.read().range(23, 23);
}

void biquadv2end::thread_newsignbit_fu_426_p3() {
    newsignbit_fu_426_p3 = p_Val2_4_fu_420_p2.read().range(23, 23);
}

void biquadv2end::thread_outDataLeft_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        outDataLeft_V_ap_vld = ap_const_logic_1;
    } else {
        outDataLeft_V_ap_vld = ap_const_logic_0;
    }
}

void biquadv2end::thread_outDataRight_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        outDataRight_V_ap_vld = ap_const_logic_1;
    } else {
        outDataRight_V_ap_vld = ap_const_logic_0;
    }
}

void biquadv2end::thread_overflow_1_fu_756_p2() {
    overflow_1_fu_756_p2 = (brmerge_i_i1_fu_746_p2.read() & tmp_16_fu_751_p2.read());
}

void biquadv2end::thread_overflow_fu_533_p2() {
    overflow_fu_533_p2 = (brmerge_i_i_fu_523_p2.read() & tmp_9_fu_528_p2.read());
}

void biquadv2end::thread_p_38_i_i1_fu_736_p2() {
    p_38_i_i1_fu_736_p2 = (carry_1_reg_1059.read() & Range1_all_ones_1_reg_1071.read());
}

void biquadv2end::thread_p_38_i_i_fu_513_p2() {
    p_38_i_i_fu_513_p2 = (carry_reg_982.read() & Range1_all_ones_reg_994.read());
}

void biquadv2end::thread_p_41_i_i1_fu_725_p2() {
    p_41_i_i1_fu_725_p2 = (Range2_all_ones_1_reg_1066.read() & tmp_15_fu_719_p2.read());
}

void biquadv2end::thread_p_41_i_i_fu_502_p2() {
    p_41_i_i_fu_502_p2 = (Range2_all_ones_reg_989.read() & tmp_1_fu_496_p2.read());
}

void biquadv2end::thread_p_Val2_2_fu_385_p2() {
    p_Val2_2_fu_385_p2 = (!tmp_8_cast_fu_381_p1.read().is_01() || !reg_299.read().is_01())? sc_lv<51>(): (sc_bigint<51>(tmp_8_cast_fu_381_p1.read()) + sc_biguint<51>(reg_299.read()));
}

void biquadv2end::thread_p_Val2_3_fu_399_p4() {
    p_Val2_3_fu_399_p4 = p_Val2_2_fu_385_p2.read().range(47, 24);
}

void biquadv2end::thread_p_Val2_4_4_fu_693_p3() {
    p_Val2_4_4_fu_693_p3 = (!underflow_reg_1026.read()[0].is_01())? sc_lv<24>(): ((underflow_reg_1026.read()[0].to_bool())? ap_const_lv24_800000: p_Val2_4_reg_970.read());
}

void biquadv2end::thread_p_Val2_4_fu_420_p2() {
    p_Val2_4_fu_420_p2 = (!p_Val2_3_fu_399_p4.read().is_01() || !tmp_5_fu_409_p1.read().is_01())? sc_lv<24>(): (sc_biguint<24>(p_Val2_3_fu_399_p4.read()) + sc_biguint<24>(tmp_5_fu_409_p1.read()));
}

void biquadv2end::thread_p_Val2_4_mux_fu_687_p3() {
    p_Val2_4_mux_fu_687_p3 = (!brmerge_i_i_i_reg_1031.read()[0].is_01())? sc_lv<24>(): ((brmerge_i_i_i_reg_1031.read()[0].to_bool())? ap_const_lv24_7FFFFF: p_Val2_4_reg_970.read());
}

void biquadv2end::thread_p_Val2_5_trunc_fu_852_p1() {
    p_Val2_5_trunc_fu_852_p1 = esl_zext<27,24>(p_Val2_5_reg_240.read());
}

void biquadv2end::thread_p_Val2_7_fu_579_p2() {
    p_Val2_7_fu_579_p2 = (!tmp_13_cast_fu_575_p1.read().is_01() || !reg_299.read().is_01())? sc_lv<51>(): (sc_bigint<51>(tmp_13_cast_fu_575_p1.read()) + sc_biguint<51>(reg_299.read()));
}

void biquadv2end::thread_p_Val2_8_fu_593_p4() {
    p_Val2_8_fu_593_p4 = p_Val2_7_fu_579_p2.read().range(47, 24);
}

void biquadv2end::thread_p_Val2_9_5_fu_805_p3() {
    p_Val2_9_5_fu_805_p3 = (!underflow_1_reg_1103.read()[0].is_01())? sc_lv<24>(): ((underflow_1_reg_1103.read()[0].to_bool())? ap_const_lv24_800000: p_Val2_9_reg_1047.read());
}

void biquadv2end::thread_p_Val2_9_fu_614_p2() {
    p_Val2_9_fu_614_p2 = (!p_Val2_8_fu_593_p4.read().is_01() || !tmp_11_fu_603_p1.read().is_01())? sc_lv<24>(): (sc_biguint<24>(p_Val2_8_fu_593_p4.read()) + sc_biguint<24>(tmp_11_fu_603_p1.read()));
}

void biquadv2end::thread_p_Val2_9_mux_fu_799_p3() {
    p_Val2_9_mux_fu_799_p3 = (!brmerge_i_i_i1_reg_1108.read()[0].is_01())? sc_lv<24>(): ((brmerge_i_i_i1_reg_1108.read()[0].to_bool())? ap_const_lv24_7FFFFF: p_Val2_9_reg_1047.read());
}

void biquadv2end::thread_p_Val2_trunc_fu_831_p1() {
    p_Val2_trunc_fu_831_p1 = esl_zext<27,24>(p_Val2_s_reg_253.read());
}

void biquadv2end::thread_p_not_i_i1_fu_740_p2() {
    p_not_i_i1_fu_740_p2 = (deleted_zeros_1_fu_714_p3.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_p_not_i_i_fu_517_p2() {
    p_not_i_i_fu_517_p2 = (deleted_zeros_fu_491_p3.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_resultLeft_V_fu_699_p3() {
    resultLeft_V_fu_699_p3 = (!underflow_not_fu_682_p2.read()[0].is_01())? sc_lv<24>(): ((underflow_not_fu_682_p2.read()[0].to_bool())? p_Val2_4_mux_fu_687_p3.read(): p_Val2_4_4_fu_693_p3.read());
}

void biquadv2end::thread_resultRight_V_fu_811_p3() {
    resultRight_V_fu_811_p3 = (!underflow_1_not_fu_794_p2.read()[0].is_01())? sc_lv<24>(): ((underflow_1_not_fu_794_p2.read()[0].to_bool())? p_Val2_9_mux_fu_799_p3.read(): p_Val2_9_5_fu_805_p3.read());
}

void biquadv2end::thread_samples_V_load11_tru_fu_827_p1() {
    samples_V_load11_tru_fu_827_p1 = esl_zext<27,24>(tmp_4_reg_1118.read());
}

void biquadv2end::thread_samples_V_load_114_t_fu_844_p1() {
    samples_V_load_114_t_fu_844_p1 = esl_zext<27,24>(tmp_17_reg_1123.read());
}

void biquadv2end::thread_samples_V_load_217_t_fu_848_p1() {
    samples_V_load_217_t_fu_848_p1 = esl_zext<27,24>(tmp_18_reg_1128.read());
}

void biquadv2end::thread_samples_V_load_320_t_fu_857_p1() {
    samples_V_load_320_t_fu_857_p1 = esl_zext<27,24>(tmp_19_reg_1133.read());
}

void biquadv2end::thread_tmp1_fu_678_p2() {
    tmp1_fu_678_p2 = (brmerge40_demorgan_i_reg_1021.read() | tmp_9_reg_1016.read());
}

void biquadv2end::thread_tmp2_demorgan_fu_767_p2() {
    tmp2_demorgan_fu_767_p2 = (p_38_i_i1_fu_736_p2.read() | brmerge40_demorgan_i_1_fu_762_p2.read());
}

void biquadv2end::thread_tmp2_fu_773_p2() {
    tmp2_fu_773_p2 = (tmp2_demorgan_fu_767_p2.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp3_fu_790_p2() {
    tmp3_fu_790_p2 = (brmerge40_demorgan_i_1_reg_1098.read() | tmp_16_reg_1093.read());
}

void biquadv2end::thread_tmp_10_fu_567_p3() {
    tmp_10_fu_567_p3 = esl_concat<24,24>(p_Val2_5_reg_240.read(), ap_const_lv24_0);
}

void biquadv2end::thread_tmp_11_fu_603_p1() {
    tmp_11_fu_603_p1 = esl_zext<24,1>(tmp_28_reg_1006.read());
}

void biquadv2end::thread_tmp_12_fu_628_p2() {
    tmp_12_fu_628_p2 = (newsignbit_1_fu_620_p3.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp_13_cast_fu_575_p1() {
    tmp_13_cast_fu_575_p1 = esl_sext<51,48>(tmp_10_fu_567_p3.read());
}

void biquadv2end::thread_tmp_13_fu_640_p4() {
    tmp_13_fu_640_p4 = p_Val2_7_fu_579_p2.read().range(50, 49);
}

void biquadv2end::thread_tmp_14_fu_656_p4() {
    tmp_14_fu_656_p4 = p_Val2_7_fu_579_p2.read().range(50, 48);
}

void biquadv2end::thread_tmp_15_fu_719_p2() {
    tmp_15_fu_719_p2 = (tmp_31_fu_707_p3.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp_16_fu_751_p2() {
    tmp_16_fu_751_p2 = (signbit_1_reg_1041.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp_17_fu_823_p1() {
    tmp_17_fu_823_p1 = array_r_q0.read().range(24-1, 0);
}

void biquadv2end::thread_tmp_18_fu_836_p1() {
    tmp_18_fu_836_p1 = array_r_q0.read().range(24-1, 0);
}

void biquadv2end::thread_tmp_19_fu_840_p1() {
    tmp_19_fu_840_p1 = array_r_q1.read().range(24-1, 0);
}

void biquadv2end::thread_tmp_1_fu_496_p2() {
    tmp_1_fu_496_p2 = (tmp_25_fu_484_p3.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp_20_fu_343_p1() {
    tmp_20_fu_343_p1 = array_r_q0.read().range(24-1, 0);
}

void biquadv2end::thread_tmp_23_fu_412_p3() {
    tmp_23_fu_412_p3 = p_Val2_2_fu_385_p2.read().range(47, 47);
}

void biquadv2end::thread_tmp_25_fu_484_p3() {
    tmp_25_fu_484_p3 = p_Val2_2_reg_959.read().range(48, 48);
}

void biquadv2end::thread_tmp_26_fu_365_p1() {
    tmp_26_fu_365_p1 = array_r_q1.read().range(24-1, 0);
}

void biquadv2end::thread_tmp_29_fu_606_p3() {
    tmp_29_fu_606_p3 = p_Val2_7_fu_579_p2.read().range(47, 47);
}

void biquadv2end::thread_tmp_2_fu_311_p2() {
    tmp_2_fu_311_p2 = (!p_s_reg_266.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(p_s_reg_266.read() == ap_const_lv3_5);
}

void biquadv2end::thread_tmp_31_fu_707_p3() {
    tmp_31_fu_707_p3 = p_Val2_7_reg_1036.read().range(48, 48);
}

void biquadv2end::thread_tmp_3_cast_fu_328_p1() {
    tmp_3_cast_fu_328_p1 = esl_zext<4,3>(p_s_reg_266.read());
}

void biquadv2end::thread_tmp_3_fu_323_p1() {
    tmp_3_fu_323_p1 = esl_zext<32,3>(p_s_reg_266.read());
}

void biquadv2end::thread_tmp_4_fu_819_p1() {
    tmp_4_fu_819_p1 = array_r_q1.read().range(24-1, 0);
}

void biquadv2end::thread_tmp_5_fu_409_p1() {
    tmp_5_fu_409_p1 = esl_zext<24,1>(tmp_22_reg_949.read());
}

void biquadv2end::thread_tmp_6_fu_446_p4() {
    tmp_6_fu_446_p4 = p_Val2_2_fu_385_p2.read().range(50, 49);
}

void biquadv2end::thread_tmp_7_fu_462_p4() {
    tmp_7_fu_462_p4 = p_Val2_2_fu_385_p2.read().range(50, 48);
}

void biquadv2end::thread_tmp_8_cast_fu_381_p1() {
    tmp_8_cast_fu_381_p1 = esl_sext<51,48>(tmp_8_fu_373_p3.read());
}

void biquadv2end::thread_tmp_8_fu_373_p3() {
    tmp_8_fu_373_p3 = esl_concat<24,24>(p_Val2_s_reg_253.read(), ap_const_lv24_0);
}

void biquadv2end::thread_tmp_9_fu_528_p2() {
    tmp_9_fu_528_p2 = (signbit_reg_964.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp_demorgan_fu_544_p2() {
    tmp_demorgan_fu_544_p2 = (p_38_i_i_fu_513_p2.read() | brmerge40_demorgan_i_fu_539_p2.read());
}

void biquadv2end::thread_tmp_fu_550_p2() {
    tmp_fu_550_p2 = (tmp_demorgan_fu_544_p2.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_tmp_s_fu_434_p2() {
    tmp_s_fu_434_p2 = (newsignbit_fu_426_p3.read() ^ ap_const_lv1_1);
}

void biquadv2end::thread_underflow_1_fu_779_p2() {
    underflow_1_fu_779_p2 = (signbit_1_reg_1041.read() & tmp2_fu_773_p2.read());
}

void biquadv2end::thread_underflow_1_not_fu_794_p2() {
    underflow_1_not_fu_794_p2 = (tmp3_fu_790_p2.read() | p_38_i_i1_reg_1088.read());
}

void biquadv2end::thread_underflow_fu_556_p2() {
    underflow_fu_556_p2 = (signbit_reg_964.read() & tmp_fu_550_p2.read());
}

void biquadv2end::thread_underflow_not_fu_682_p2() {
    underflow_not_fu_682_p2 = (tmp1_fu_678_p2.read() | p_38_i_i_reg_1011.read());
}

void biquadv2end::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataRight_V_ap_vld.read()) || esl_seteq<1,1,1>(ap_const_logic_0, inDataLeft_V_ap_vld.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_2_fu_311_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
            break;
    }
}

void biquadv2end::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inDataLeft_V\" :  \"" << inDataLeft_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inDataLeft_V_ap_vld\" :  \"" << inDataLeft_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"inDataLeft_V_ap_ack\" :  \"" << inDataLeft_V_ap_ack.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inDataRight_V\" :  \"" << inDataRight_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inDataRight_V_ap_vld\" :  \"" << inDataRight_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"inDataRight_V_ap_ack\" :  \"" << inDataRight_V_ap_ack.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_AWVALID\" :  \"" << s_axi_biquadv2_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_AWREADY\" :  \"" << s_axi_biquadv2_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_AWADDR\" :  \"" << s_axi_biquadv2_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_WVALID\" :  \"" << s_axi_biquadv2_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_WREADY\" :  \"" << s_axi_biquadv2_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_WDATA\" :  \"" << s_axi_biquadv2_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_WSTRB\" :  \"" << s_axi_biquadv2_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_ARVALID\" :  \"" << s_axi_biquadv2_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_ARREADY\" :  \"" << s_axi_biquadv2_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_ARADDR\" :  \"" << s_axi_biquadv2_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_RVALID\" :  \"" << s_axi_biquadv2_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_RREADY\" :  \"" << s_axi_biquadv2_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_RDATA\" :  \"" << s_axi_biquadv2_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_RRESP\" :  \"" << s_axi_biquadv2_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_BVALID\" :  \"" << s_axi_biquadv2_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_biquadv2_BREADY\" :  \"" << s_axi_biquadv2_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_biquadv2_BRESP\" :  \"" << s_axi_biquadv2_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

