-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity biquadv2 is
generic (
    C_S_AXI_BIQUADV2_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_BIQUADV2_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_biquadv2_AWVALID : IN STD_LOGIC;
    s_axi_biquadv2_AWREADY : OUT STD_LOGIC;
    s_axi_biquadv2_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BIQUADV2_ADDR_WIDTH-1 downto 0);
    s_axi_biquadv2_WVALID : IN STD_LOGIC;
    s_axi_biquadv2_WREADY : OUT STD_LOGIC;
    s_axi_biquadv2_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_BIQUADV2_DATA_WIDTH-1 downto 0);
    s_axi_biquadv2_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_BIQUADV2_DATA_WIDTH/8-1 downto 0);
    s_axi_biquadv2_ARVALID : IN STD_LOGIC;
    s_axi_biquadv2_ARREADY : OUT STD_LOGIC;
    s_axi_biquadv2_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BIQUADV2_ADDR_WIDTH-1 downto 0);
    s_axi_biquadv2_RVALID : OUT STD_LOGIC;
    s_axi_biquadv2_RREADY : IN STD_LOGIC;
    s_axi_biquadv2_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_BIQUADV2_DATA_WIDTH-1 downto 0);
    s_axi_biquadv2_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_biquadv2_BVALID : OUT STD_LOGIC;
    s_axi_biquadv2_BREADY : IN STD_LOGIC;
    s_axi_biquadv2_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of biquadv2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "biquadv2,hls_ip_2017_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.416000,HLS_SYN_LAT=40,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=3,HLS_SYN_FF=1011,HLS_SYN_LUT=1041}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal b0_a0_V : STD_LOGIC_VECTOR (26 downto 0);
    signal b1_a0_V : STD_LOGIC_VECTOR (26 downto 0);
    signal b2_a0_V : STD_LOGIC_VECTOR (26 downto 0);
    signal a1_a0_V : STD_LOGIC_VECTOR (26 downto 0);
    signal a2_a0_V : STD_LOGIC_VECTOR (26 downto 0);
    signal inData_V : STD_LOGIC_VECTOR (23 downto 0);
    signal outData_V_ap_vld : STD_LOGIC;
    signal coeffs_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal coeffs_V_ce0 : STD_LOGIC;
    signal coeffs_V_we0 : STD_LOGIC;
    signal coeffs_V_d0 : STD_LOGIC_VECTOR (26 downto 0);
    signal coeffs_V_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal coeffs_V_ce1 : STD_LOGIC;
    signal coeffs_V_we1 : STD_LOGIC;
    signal coeffs_V_d1 : STD_LOGIC_VECTOR (26 downto 0);
    signal coeffs_V_q1 : STD_LOGIC_VECTOR (26 downto 0);
    signal samples_V_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal samples_V_ce0 : STD_LOGIC;
    signal samples_V_we0 : STD_LOGIC;
    signal samples_V_d0 : STD_LOGIC_VECTOR (23 downto 0);
    signal samples_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal samples_V_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal samples_V_ce1 : STD_LOGIC;
    signal samples_V_we1 : STD_LOGIC;
    signal samples_V_d1 : STD_LOGIC_VECTOR (23 downto 0);
    signal samples_V_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal reg_218 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal inData_V_read_reg_485 : STD_LOGIC_VECTOR (23 downto 0);
    signal a2_a0_V_read_reg_490 : STD_LOGIC_VECTOR (26 downto 0);
    signal a1_a0_V_read_reg_495 : STD_LOGIC_VECTOR (26 downto 0);
    signal b2_a0_V_read_reg_500 : STD_LOGIC_VECTOR (26 downto 0);
    signal i_V_fu_230_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_V_reg_508 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_1_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal coeffs_V_load_reg_523 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_249_p2 : STD_LOGIC_VECTOR (50 downto 0);
    signal p_Val2_1_reg_538 : STD_LOGIC_VECTOR (50 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_10_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_2_fu_275_p2 : STD_LOGIC_VECTOR (50 downto 0);
    signal p_Val2_2_reg_548 : STD_LOGIC_VECTOR (50 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal signbit_reg_553 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_fu_309_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_4_reg_559 : STD_LOGIC_VECTOR (23 downto 0);
    signal newsignbit_fu_315_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_reg_565 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_reg_578 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_reg_583 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_reg_590 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i_i_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i_i_reg_595 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_9_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_600 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_reg_605 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i_reg_615 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_V_fu_477_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal p_Val2_s_reg_193 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_s_reg_207 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_236_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_7_fu_263_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_7_cast_fu_271_p1 : STD_LOGIC_VECTOR (50 downto 0);
    signal p_Val2_3_fu_288_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_4_fu_298_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_11_fu_301_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_335_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_8_fu_351_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_13_fu_373_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_41_i_i_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_380_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_i_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_396_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_demorgan_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_not_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_mux_fu_465_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Val2_4_4_fu_471_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);

    component biquadv2_mul_27s_bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (26 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (50 downto 0) );
    end component;


    component biquadv2_coeffs_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (26 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (26 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component biquadv2_samples_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (23 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component biquadv2_biquadv2_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        b0_a0_V : OUT STD_LOGIC_VECTOR (26 downto 0);
        b1_a0_V : OUT STD_LOGIC_VECTOR (26 downto 0);
        b2_a0_V : OUT STD_LOGIC_VECTOR (26 downto 0);
        a1_a0_V : OUT STD_LOGIC_VECTOR (26 downto 0);
        a2_a0_V : OUT STD_LOGIC_VECTOR (26 downto 0);
        inData_V : OUT STD_LOGIC_VECTOR (23 downto 0);
        outData_V : IN STD_LOGIC_VECTOR (23 downto 0);
        outData_V_ap_vld : IN STD_LOGIC );
    end component;



begin
    coeffs_V_U : component biquadv2_coeffs_V
    generic map (
        DataWidth => 27,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => coeffs_V_address0,
        ce0 => coeffs_V_ce0,
        we0 => coeffs_V_we0,
        d0 => coeffs_V_d0,
        address1 => coeffs_V_address1,
        ce1 => coeffs_V_ce1,
        we1 => coeffs_V_we1,
        d1 => coeffs_V_d1,
        q1 => coeffs_V_q1);

    samples_V_U : component biquadv2_samples_V
    generic map (
        DataWidth => 24,
        AddressRange => 5,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => samples_V_address0,
        ce0 => samples_V_ce0,
        we0 => samples_V_we0,
        d0 => samples_V_d0,
        q0 => samples_V_q0,
        address1 => samples_V_address1,
        ce1 => samples_V_ce1,
        we1 => samples_V_we1,
        d1 => samples_V_d1,
        q1 => samples_V_q1);

    biquadv2_biquadv2_s_axi_U : component biquadv2_biquadv2_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_BIQUADV2_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_BIQUADV2_DATA_WIDTH)
    port map (
        AWVALID => s_axi_biquadv2_AWVALID,
        AWREADY => s_axi_biquadv2_AWREADY,
        AWADDR => s_axi_biquadv2_AWADDR,
        WVALID => s_axi_biquadv2_WVALID,
        WREADY => s_axi_biquadv2_WREADY,
        WDATA => s_axi_biquadv2_WDATA,
        WSTRB => s_axi_biquadv2_WSTRB,
        ARVALID => s_axi_biquadv2_ARVALID,
        ARREADY => s_axi_biquadv2_ARREADY,
        ARADDR => s_axi_biquadv2_ARADDR,
        RVALID => s_axi_biquadv2_RVALID,
        RREADY => s_axi_biquadv2_RREADY,
        RDATA => s_axi_biquadv2_RDATA,
        RRESP => s_axi_biquadv2_RRESP,
        BVALID => s_axi_biquadv2_BVALID,
        BREADY => s_axi_biquadv2_BREADY,
        BRESP => s_axi_biquadv2_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        b0_a0_V => b0_a0_V,
        b1_a0_V => b1_a0_V,
        b2_a0_V => b2_a0_V,
        a1_a0_V => a1_a0_V,
        a2_a0_V => a2_a0_V,
        inData_V => inData_V,
        outData_V => p_Val2_s_reg_193,
        outData_V_ap_vld => outData_V_ap_vld);

    biquadv2_mul_27s_bkb_U0 : component biquadv2_mul_27s_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 27,
        din1_WIDTH => 24,
        dout_WIDTH => 51)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => coeffs_V_load_reg_523,
        din1 => reg_218,
        ce => ap_const_logic_1,
        dout => grp_fu_249_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    p_Val2_s_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                p_Val2_s_reg_193 <= result_V_fu_477_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                p_Val2_s_reg_193 <= ap_const_lv24_0;
            end if; 
        end if;
    end process;

    p_s_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                p_s_reg_207 <= i_V_reg_508;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                p_s_reg_207 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                reg_218 <= samples_V_q1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                reg_218 <= samples_V_q0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                Range1_all_ones_reg_583 <= Range1_all_ones_fu_361_p2;
                Range1_all_zeros_reg_590 <= Range1_all_zeros_fu_367_p2;
                Range2_all_ones_reg_578 <= Range2_all_ones_fu_345_p2;
                carry_reg_571 <= carry_fu_329_p2;
                newsignbit_reg_565 <= p_Val2_4_fu_309_p2(23 downto 23);
                p_Val2_2_reg_548 <= p_Val2_2_fu_275_p2;
                p_Val2_4_reg_559 <= p_Val2_4_fu_309_p2;
                signbit_reg_553 <= p_Val2_2_fu_275_p2(50 downto 50);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                a1_a0_V_read_reg_495 <= a1_a0_V;
                a2_a0_V_read_reg_490 <= a2_a0_V;
                b2_a0_V_read_reg_500 <= b2_a0_V;
                inData_V_read_reg_485 <= inData_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                brmerge40_demorgan_i_reg_605 <= brmerge40_demorgan_i_fu_428_p2;
                brmerge_i_i_i_reg_615 <= brmerge_i_i_i_fu_450_p2;
                p_38_i_i_reg_595 <= p_38_i_i_fu_402_p2;
                tmp_9_reg_600 <= tmp_9_fu_417_p2;
                underflow_reg_610 <= underflow_fu_445_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                coeffs_V_load_reg_523 <= coeffs_V_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_V_reg_508 <= i_V_fu_230_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                p_Val2_1_reg_538 <= grp_fu_249_p2;
                tmp_10_reg_543 <= grp_fu_249_p2(23 downto 23);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, tmp_1_fu_224_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_1_fu_224_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    Range1_all_ones_fu_361_p2 <= "1" when (tmp_8_fu_351_p4 = ap_const_lv3_7) else "0";
    Range1_all_zeros_fu_367_p2 <= "1" when (tmp_8_fu_351_p4 = ap_const_lv3_0) else "0";
    Range2_all_ones_fu_345_p2 <= "1" when (tmp_6_fu_335_p4 = ap_const_lv2_3) else "0";
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    brmerge40_demorgan_i_fu_428_p2 <= (newsignbit_reg_565 and deleted_ones_fu_396_p3);
    brmerge_i_i_fu_412_p2 <= (newsignbit_reg_565 or p_not_i_i_fu_406_p2);
    brmerge_i_i_i_fu_450_p2 <= (underflow_fu_445_p2 or overflow_fu_422_p2);
    carry_fu_329_p2 <= (tmp_11_fu_301_p3 and tmp_s_fu_323_p2);

    coeffs_V_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            coeffs_V_address0 <= ap_const_lv3_4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            coeffs_V_address0 <= ap_const_lv3_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            coeffs_V_address0 <= ap_const_lv3_0;
        else 
            coeffs_V_address0 <= "XXX";
        end if; 
    end process;


    coeffs_V_address1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state4, tmp_2_fu_236_p1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            coeffs_V_address1 <= tmp_2_fu_236_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            coeffs_V_address1 <= ap_const_lv3_3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            coeffs_V_address1 <= ap_const_lv3_1;
        else 
            coeffs_V_address1 <= "XXX";
        end if; 
    end process;


    coeffs_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            coeffs_V_ce0 <= ap_const_logic_1;
        else 
            coeffs_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    coeffs_V_ce1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            coeffs_V_ce1 <= ap_const_logic_1;
        else 
            coeffs_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    coeffs_V_d0_assign_proc : process(ap_CS_fsm_state1, b0_a0_V, a2_a0_V_read_reg_490, b2_a0_V_read_reg_500, ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            coeffs_V_d0 <= a2_a0_V_read_reg_490;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            coeffs_V_d0 <= b2_a0_V_read_reg_500;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            coeffs_V_d0 <= b0_a0_V;
        else 
            coeffs_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    coeffs_V_d1_assign_proc : process(ap_CS_fsm_state1, b1_a0_V, a1_a0_V_read_reg_495, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            coeffs_V_d1 <= a1_a0_V_read_reg_495;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            coeffs_V_d1 <= b1_a0_V;
        else 
            coeffs_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    coeffs_V_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            coeffs_V_we0 <= ap_const_logic_1;
        else 
            coeffs_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    coeffs_V_we1_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            coeffs_V_we1 <= ap_const_logic_1;
        else 
            coeffs_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    deleted_ones_fu_396_p3 <= 
        p_41_i_i_fu_391_p2 when (carry_reg_571(0) = '1') else 
        Range1_all_ones_reg_583;
    deleted_zeros_fu_380_p3 <= 
        Range1_all_ones_reg_583 when (carry_reg_571(0) = '1') else 
        Range1_all_zeros_reg_590;
    i_V_fu_230_p2 <= std_logic_vector(unsigned(p_s_reg_207) + unsigned(ap_const_lv3_1));
    newsignbit_fu_315_p3 <= p_Val2_4_fu_309_p2(23 downto 23);

    outData_V_ap_vld_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            outData_V_ap_vld <= ap_const_logic_1;
        else 
            outData_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    overflow_fu_422_p2 <= (brmerge_i_i_fu_412_p2 and tmp_9_fu_417_p2);
    p_38_i_i_fu_402_p2 <= (carry_reg_571 and Range1_all_ones_reg_583);
    p_41_i_i_fu_391_p2 <= (Range2_all_ones_reg_578 and tmp_5_fu_385_p2);
    p_Val2_2_fu_275_p2 <= std_logic_vector(signed(tmp_7_cast_fu_271_p1) + signed(p_Val2_1_reg_538));
    p_Val2_3_fu_288_p4 <= p_Val2_2_fu_275_p2(47 downto 24);
    p_Val2_4_4_fu_471_p3 <= 
        ap_const_lv24_800000 when (underflow_reg_610(0) = '1') else 
        p_Val2_4_reg_559;
    p_Val2_4_fu_309_p2 <= std_logic_vector(unsigned(p_Val2_3_fu_288_p4) + unsigned(tmp_4_fu_298_p1));
    p_Val2_4_mux_fu_465_p3 <= 
        ap_const_lv24_7FFFFF when (brmerge_i_i_i_reg_615(0) = '1') else 
        p_Val2_4_reg_559;
    p_not_i_i_fu_406_p2 <= (deleted_zeros_fu_380_p3 xor ap_const_lv1_1);
    result_V_fu_477_p3 <= 
        p_Val2_4_mux_fu_465_p3 when (underflow_not_fu_460_p2(0) = '1') else 
        p_Val2_4_4_fu_471_p3;

    samples_V_address0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state4, tmp_1_fu_224_p2, ap_CS_fsm_state3, tmp_2_fu_236_p1, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            samples_V_address0 <= ap_const_lv3_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_1_fu_224_p2 = ap_const_lv1_1)))) then 
            samples_V_address0 <= ap_const_lv3_3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_1_fu_224_p2 = ap_const_lv1_0))) then 
            samples_V_address0 <= tmp_2_fu_236_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            samples_V_address0 <= ap_const_lv3_0;
        else 
            samples_V_address0 <= "XXX";
        end if; 
    end process;


    samples_V_address1_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            samples_V_address1 <= ap_const_lv3_2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            samples_V_address1 <= ap_const_lv3_4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            samples_V_address1 <= ap_const_lv3_1;
        else 
            samples_V_address1 <= "XXX";
        end if; 
    end process;


    samples_V_ce0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state4, tmp_1_fu_224_p2, ap_CS_fsm_state3, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_1_fu_224_p2 = ap_const_lv1_0)) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (tmp_1_fu_224_p2 = ap_const_lv1_1)))) then 
            samples_V_ce0 <= ap_const_logic_1;
        else 
            samples_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_V_ce1_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state4, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            samples_V_ce1 <= ap_const_logic_1;
        else 
            samples_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_V_d0_assign_proc : process(ap_CS_fsm_state11, inData_V_read_reg_485, p_Val2_s_reg_193, ap_CS_fsm_state3, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            samples_V_d0 <= p_Val2_s_reg_193;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            samples_V_d0 <= inData_V_read_reg_485;
        else 
            samples_V_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    samples_V_d1_assign_proc : process(samples_V_q0, reg_218, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            samples_V_d1 <= reg_218;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            samples_V_d1 <= samples_V_q0;
        else 
            samples_V_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    samples_V_we0_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state3, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            samples_V_we0 <= ap_const_logic_1;
        else 
            samples_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_V_we1_assign_proc : process(ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            samples_V_we1 <= ap_const_logic_1;
        else 
            samples_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_456_p2 <= (brmerge40_demorgan_i_reg_605 or tmp_9_reg_600);
    tmp_11_fu_301_p3 <= p_Val2_2_fu_275_p2(47 downto 47);
    tmp_13_fu_373_p3 <= p_Val2_2_reg_548(48 downto 48);
    tmp_1_fu_224_p2 <= "1" when (p_s_reg_207 = ap_const_lv3_5) else "0";
    tmp_2_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_s_reg_207),32));
    tmp_4_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_reg_543),24));
    tmp_5_fu_385_p2 <= (tmp_13_fu_373_p3 xor ap_const_lv1_1);
    tmp_6_fu_335_p4 <= p_Val2_2_fu_275_p2(50 downto 49);
        tmp_7_cast_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_263_p3),51));

    tmp_7_fu_263_p3 <= (p_Val2_s_reg_193 & ap_const_lv24_0);
    tmp_8_fu_351_p4 <= p_Val2_2_fu_275_p2(50 downto 48);
    tmp_9_fu_417_p2 <= (signbit_reg_553 xor ap_const_lv1_1);
    tmp_demorgan_fu_433_p2 <= (p_38_i_i_fu_402_p2 or brmerge40_demorgan_i_fu_428_p2);
    tmp_fu_439_p2 <= (tmp_demorgan_fu_433_p2 xor ap_const_lv1_1);
    tmp_s_fu_323_p2 <= (newsignbit_fu_315_p3 xor ap_const_lv1_1);
    underflow_fu_445_p2 <= (signbit_reg_553 and tmp_fu_439_p2);
    underflow_not_fu_460_p2 <= (tmp1_fu_456_p2 or p_38_i_i_reg_595);
end behav;
